Included "Mathematical bold digits" in Agda input mode under `\Bx`.
agda/agda pull request #2391
Opened 2017-01-09 17:50 UTC by pepijnkokke

2017-01-09 17:58 UTC, asr requested changes
You added changelog information for Agda 2.5.2. The information should be added for Agda 2.5.3 (top of the changelog file) under a new section called 'Emacs mode'.

2017-01-09 20:28 UTC, asr approved these changes

2017-01-09 20:28 UTC, merged

2017-01-09 20:29 UTC, asr commented
Thanks!

2017-01-10 17:24 UTC, andreasabel commented
Merged too early!  The whitespace check failed.  One cannot be paranoid enough, it seems. ;-)