[ warning ] user defined warnings
agda/agda pull request #3030
Opened 2018-04-13 15:49 UTC by gallais

{-# WARNING_ON_USAGE QName Message #-} displays the Message whenever
QName is used. This would typically be used to deprecate a function
in favour of a more modern / idiomatic replacement.

2018-04-13 16:02 UTC, UlfNorell requested changes
Nice! Changelog and manual and you're golden 👍

2018-04-13 16:04 UTC, MatthewDaggitt commented
Awesome feature! Is there any ability to add multiple names? Or do you have to declare the whole message again for each name?

2018-04-13 18:44 UTC, gallais commented
At the moment you have to repeat it which makes sense to me if you're
going to suggest a replacement for the deprecated name!

However, I suppose we could maybe switch to `{-# WARNING_ON_USAGE [QName] StringLiteral #-}`.
I'd have to have another look at the parser to see how to do that.

2018-04-13 22:56 UTC, MatthewDaggitt commented
> At the moment you have to repeat it which makes sense to me if you're
going to suggest a replacement for the deprecated name!

Yup, you're absolutely right. I was trying to be lazy, but yes we'd want to suggest a replacement for each name.

2018-04-16 13:29 UTC, gallais commented
I have switched to using a string literal as the message because that's
what it is. I had to modify the lexer to do that (string literals where not
recognized in pragmas) but it seems to work well now (and it gave me
an excuse to learn a bit about Alex).

2018-04-17 14:50 UTC, merged