Mend holes in mathematical script letters
agda/agda pull request #3047
Opened 2018-05-01 09:57 UTC by fredefox

I just found out that there are "holes" in the unicode table explaining why there is no `MATHEMATICAL SCRIPT CAPITAL B`, it already existed as `SCRIPT CAPITAL B`. I've added these.

See also [this SO post](https://stackoverflow.com/questions/47206070/why-are-there-holes-in-the-unicode-table?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa).

2018-05-01 10:01 UTC, UlfNorell commented
Nice. Can you make the PR against `stable-2.5`?

2018-05-01 10:25 UTC, gallais requested changes

2018-05-01 10:25 UTC, gallais commented on src/data/emacs-mode/agda-input.el
> +  ("Mce" . ("ℰ"))
This appears to be `SCRIPT CAPITAL E` and not the lowercase version

2018-05-07 11:29 UTC, fredefox commented
Closing in favor of #3048

2018-05-07 11:29 UTC, closed without merging