generalize (second version)
agda/agda pull request #3071
Opened 2018-05-22 16:38 UTC by divipp

Second version of 'generalize'

TODO:

- documentation in `doc/release-notes`
- more tests

Known bugs & limitations:

- bug: generalizable variables escape their scope
- more robust implementation: Currently the metavariables in the types of generalizable variables are solved during type inference, and later these metavariables are reset to unsolved state. Better would be to add fresh metavariables each time.
- The generalized type should be build up from outside to inside, adding outer bindings first. Currently it is done in the other way around, so metavariables are solved before the generalization begins, but not solved during the generalization. See <https://lists.chalmers.se/pipermail/agda/2018/010188.html>
- feature request: support generalize in the rhs <https://github.com/divipp/agda/issues/4>
- feature request: export generalizable variables
- other bugs: <https://github.com/divipp/agda/issues>

2018-05-23 13:06 UTC, UlfNorell commented
Looks good to me.

@asr Should we wait to merge until after the `2.5.4` release to avoid conflicts with potential last-minute bug fixes?

2018-05-23 13:10 UTC, asr commented
> @asr Should we wait to merge until after the `2.5.4` release to avoid conflicts with potential last-minute bug fixes?

Yes, please!

2018-06-04 14:26 UTC, andreasabel requested changes
Nice clean code!
Please document all new constructors and record fields, and the major functions.  See:
https://github.com/andreasabel/haskell-style-guide/blob/master/haskell-style.md

2018-06-04 14:26 UTC, andreasabel commented on src/full/Agda/TypeChecking/Monad/Base.hs
> +  , stPostGeneralizables      :: !(Map QName ((Set QName, ArgInfo), MetaStore))
Please haddockument!

2018-06-04 14:26 UTC, andreasabel commented on src/full/Agda/TypeChecking/Monad/Base.hs
> +stGeneralizedVars :: Lens' (Maybe (Set QName)) TCState
Please haddockument!

2018-06-04 14:26 UTC, andreasabel commented on src/full/Agda/TypeChecking/Monad/Base.hs
> +stGeneralizableMetas :: Lens' (Map QName ((Set QName, ArgInfo), MetaStore)) TCState
Please haddockument!

2018-06-04 14:26 UTC, andreasabel commented on src/full/Agda/TypeChecking/Rules/Decl.hs
> +filterGeneralizables :: TCM ()
Please haddockument!

2018-06-04 14:26 UTC, andreasabel commented on src/full/Agda/TypeChecking/Rules/Decl.hs
> +registerGeneralize :: Set QName -> ArgInfo -> QName -> TCM a -> TCM a
Please haddockument!

2018-06-04 14:26 UTC, andreasabel commented on src/full/Agda/TypeChecking/Rules/Term.hs
> +            noFunctionsIntoSize t0 t'
Please do not cut-and paste, rather generalize the code (extract a common auxiliary function).

2018-06-04 14:26 UTC, andreasabel commented on src/full/Agda/TypeChecking/Rules/Term.hs
> +checkGeneralized :: Set.Set QName -> TCM Type -> TCM (Type, Type)
Please haddockument!
At some point, please include a longer comment giving a survey of the Generalize feature and how the components interact.

2018-06-04 14:26 UTC, andreasabel commented on src/full/Agda/TypeChecking/Rules/Term.hs
> +                me {mvInstantiation = InstV [] (error ("meta var " ++ show n ++ " was generalized"))} -- TODO
Please say what is TODO here.

2018-06-04 14:26 UTC, andreasabel commented on src/full/Agda/Syntax/Concrete.hs
> +  | Generalized Expr
Please haddockument!

2018-06-05 06:47 UTC, UlfNorell commented
@divipp I've invited you to the Agda github group so you should be getting commit rights to the repo. I'm merging this now and you can address @andreasabel's comments on `stable-2.5` directly as you have the time.

2018-06-05 06:47 UTC, merged

2018-06-07 12:20 UTC, nad commented
There should also be some documentation of the feature in the user manual, and some text in the changelog.

2018-06-07 12:27 UTC, UlfNorell commented
Documentation: #3116.

2018-10-15 23:38 UTC, ice1000 commented
It looks like @divipp still haven't accepted the invitation, you may checkout this link:
https://github.com/orgs/agda/invitations