[ new ] Fewer postulates needed for Primitive types
agda/agda pull request #3174
Opened 2018-08-08 14:22 UTC by gallais

Looking at our attempt to make (most of) the standard library compile with the `--safe` flag
(cf. agda/agda-stdlib/pull/414), it would be nice to be able to drop some of the `postulate`s
in `Agda.Builtin.*`.

This is what I came up with. It does allow me to typecheck all of our target modules
in safe mode.

But seeing how some of these builtins trigger [special cases](https://github.com/agda/agda/blob/master/src/full/Agda/TypeChecking/Rules/Builtin.hs#L791) inserting extra (invisible) pragmas,
I can't say for sure I haven't broken anything. Opinions?

2018-08-08 18:05 UTC, gallais commented
Based on the tests, it looks like we *do* miss some of these silent pragmas.
Here is the error raised by the compilation test case `Succeed/ForeignPragma`:

```
test/Common/IO.agda:36,1-49
The type String → IO ⊤ cannot be translated to a corresponding
Haskell type, because it contains String which does not have a
COMPILE pragma.
Possible fix: add a pragma
  {-# COMPILE GHC String = type HsT #-}
for a suitable Haskell type HsT.
```

A solution would be to add a field for a `TCM ()` to `BuiltinInfo` and run that when
the `BUILTIN` is declared.

2018-08-15 08:20 UTC, UlfNorell requested changes
The special cases should simply be moved to `bindBuiltinNoDef`, no? Otherwise this looks sensible.

2018-08-16 10:11 UTC, gallais commented
Current problem: BUILTIN-bound names are assigned `noFixity` which means that `♯_`
gets the wrong level. I should be able to check whether there is a pre-existing fixity
declaration and use that instead.

I'll look into it after lunch.

2018-08-16 11:07 UTC, UlfNorell commented on src/full/Agda/TypeChecking/Rules/Builtin.hs
> +   case builtinDesc <$> findBuiltinInfo b of
Accidental space!! 🙀

2018-08-16 15:28 UTC, gallais commented on src/full/Agda/Syntax/Translation/AbstractToConcrete.hs
>        x <- toConcrete x
grrr another extra space

2018-08-16 19:17 UTC, gallais commented
The [previous build](https://travis-ci.org/agda/agda/builds/416906115) succeeded for everything except haddock so I've cancelled all the jobs
[except for the haddock one](https://travis-ci.org/agda/agda/builds/416961319) on this one. If it is successful then we're good to go!

2018-08-16 19:25 UTC, UlfNorell approved these changes

2018-08-16 19:43 UTC, merged

2018-09-04 13:08 UTC, andreasabel commented
Well, this is in part to be blamed on me, since I started builtins without postulates for sized types.  There, the rationale was that things like `SizeUniv` cannot be typed.  At that time, someone remarked that pragmas cannot be ignored any longer in reading code since they add symbols to the scope.
With the present PR, we seem to have abandoned the "pragmas are just technical detail to be ignored on first reading" altogether.  It would be consequent to add a proper syntax for builtins now that does not look like a comment, similar to `primitive`.
```agda
builtin
  STRING String
  EQUALITY _==_
```