Simplify and consolidate GHC version conditions
agda/agda pull request #3726
Opened 2019-04-26 20:45 UTC by erydo

More info in the commit comments. This is intended to be a non-breaking, no-op, cleanup change.

In summary, this consolidates Cabal and build macro conditions that check for effectively the same GHC version ranges.
For example, "strictly after 7.10" means the same as "8.0 or above" because there were no GHC releases in between.
Some checks referring to 7.08 were redundant, since support had been removed for that version.

2019-04-26 20:59 UTC, asr commented
@erydo, let me know when your PR passes the Travis tests.

2019-04-27 08:05 UTC, UlfNorell approved these changes

2019-04-27 18:41 UTC, erydo commented
@asr — This PR passes Travis

2019-04-29 00:46 UTC, asr requested changes
I don't understand the title and the message of [this](4838b0aeea56bb6df01dfa178cbfcb016251e9d6) commit. Note that for example `__GLASGOW_HASKELL__== 8.0.2` doesn't is true with GHC 8.0.2 but with GHC 8.2.*.

2019-04-29 05:02 UTC, UlfNorell commented
Yes the commit message is a little confused (`802` means `8.2.*`, not `8.0.2`). But it goes through Travis so clearly relaxing the bound to 800 was the right thing?

2019-04-29 16:16 UTC, erydo commented
Yes, you're both right.

I'd originally misunderstood the number padding of the `__GLASGOW_HASKELL__` macro and had another change in that commit (original: 1a54099107570193a1bb1d40d38b6ae750f9b1fd) and Travis failed. After [rereading the docs](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/intro.html#ghc-version-numbering-policy), I removed the invalid change (current: 4838b0aeea56bb6df01dfa178cbfcb016251e9d6) but forgot to rewrite the message.

The change that stayed in place _is_ valid for 8.0.0+. (The `Any` type doesn't show up in Hackage for `base-4.9.0.0` like it does for [`base-4.11.0.0`](https://hackage.haskell.org/package/base-4.11.0.0/docs/GHC-Exts.html#t:Any), but it _is_ exported since all of [`module GHC.Prim` is exported by `GHC.Exts`](https://hackage.haskell.org/package/base-4.9.0.0/docs/src/GHC.Exts.html)).

If it's worthwhile I can rewrite the message, though it'll trigger rebuilds on this branch and the two downstream ones (#3728 and #3729). Thoughts?

2019-04-30 01:47 UTC, asr commented
I suggest to fix the message. In fact, since the change in 4838b0aeea56bb6df01dfa178cbfcb016251e9d6 (although valid) isn't necessary, I suggest to remove this commit for avoiding a new change when the support for GHC 8.0.2 be removed.

2019-04-30 04:50 UTC, UlfNorell commented
> I suggest to remove this commit for avoiding a new change when the support for GHC 8.0.2 be removed.

Keeping the change means that we can get rid of the CPP directive completely in the next PR (dropping 7.10 support). Removing the commit means we "have to" wait with that until dropping 8.0.2. I can see the point in changing the commit message but skipping the commit completely makes no sense.

2019-04-30 11:31 UTC, asr commented
> I can see the point in changing the commit message but skipping the commit completely makes no sense.

You are right (I hadn't in mind the PR for dropping support for GHC 7.10.3).

2019-04-30 14:01 UTC, erydo commented
Ok, I'll go ahead and update the commit message.

2019-04-30 14:18 UTC, erydo commented
Ok, that commit message has been rewritten. The contents of the branch itself is unchanged: https://github.com/erydo/agda/compare/636a6d5..753f188

Have also rebased the other branches on top of that.

2019-04-30 14:44 UTC, asr approved these changes

2019-04-30 19:03 UTC, merged

2019-04-30 19:03 UTC, asr commented
Thanks!

2020-07-18 19:40 UTC, rwe commented
Just a note here in case anyone in the future tries to make sense of the confusing commit message: looks like the commit that was merged (753f188) was the one prior to the updated message. Probably locally merged without fetching first. Only noticed this while pruning local branches and git complained that the branch had unmerged changes. That may have also affected #3279, but that was over a year ago so I imagine it's all sorted out by now.