Get rid of codata definitions
agda/agda pull request #4047
Opened 2019-08-31 22:02 UTC by ggreif

This is a draft!

There are still a few hits with `git grep -i CoData` in need of cleaning up.

Hints, suggestions welcome. Encouragement about the general direction too :-)

Fixes #4046.

2019-09-17 08:48 UTC, andreasabel commented
It seems like even we revive `codata` as a keyword for declaring higher coindutive types, it would not generate a variant of `data` declarations, thus, most of the cleanup code in this PR would be good to merge.

2019-09-17 09:12 UTC, ggreif commented
Any ideas which hunks should be preserved? Or should there be a clean cut and then bring back specific hunks?

2019-09-17 09:36 UTC, andreasabel requested changes
Please keep `codata` as a reserved word in the lexer.  (I marked these hunks.)

The rest can go.

2019-09-17 09:36 UTC, andreasabel commented on src/full/Agda/Syntax/Parser/Lexer.x
> -<0,code> codata         { keyword KwCoData }
Please keep!

2019-09-17 09:36 UTC, andreasabel commented on src/full/Agda/Syntax/Parser/Parser.y
> -    'codata'                  { TokKeyword KwCoData $$ }
Please keep!

2019-09-17 09:36 UTC, andreasabel commented on src/full/Agda/Syntax/Parser/Parser.y
> -    | 'codata'                  { TokKeyword KwCoData $1 }
Please keep!

2019-09-17 09:36 UTC, andreasabel commented on src/full/Agda/Syntax/Parser/Tokens.hs
> -        = KwLet | KwIn | KwWhere | KwData | KwCoData | KwDo
Please keep!

2019-09-17 12:33 UTC, ggreif commented on src/full/Agda/Syntax/Parser/Tokens.hs
> -        = KwLet | KwIn | KwWhere | KwData | KwCoData | KwDo
Done.

2019-09-17 12:33 UTC, ggreif commented on src/full/Agda/Syntax/Parser/Lexer.x
> -<0,code> codata         { keyword KwCoData }
Done.

2019-09-17 12:33 UTC, ggreif commented on src/full/Agda/Syntax/Parser/Parser.y
> -    'codata'                  { TokKeyword KwCoData $$ }
Done.

2019-09-17 12:33 UTC, ggreif commented on src/full/Agda/Syntax/Parser/Parser.y
> -    | 'codata'                  { TokKeyword KwCoData $1 }
Done.

2019-09-17 12:39 UTC, ggreif commented
@andreasabel thanks for reviewing!

2019-09-17 12:41 UTC, ggreif commented
@andreasabel any idea how to reformulate the comment in src/full/Agda/TypeChecking/Rules/Builtin/Coinduction.hs:60 ?

2019-11-29 14:19 UTC, ggreif commented
> @andreasabel any idea how to reformulate the comment in src/full/Agda/TypeChecking/Rules/Builtin/Coinduction.hs:60 ?

@andreasabel ping

2019-12-14 19:01 UTC, ggreif commented
@andreasabel this is still blocked by the "requested changes" label you added. What can I do?

2019-12-17 16:02 UTC, jespercockx commented
Since there is no reply from @andreasabel and the release is coming close, I will go ahead and merge this in. We can always update the comment later if necessary.

2019-12-17 16:02 UTC, merged