enable anonymous import: `import Whatever as _`
agda/agda pull request #4270
Opened 2019-12-08 00:04 UTC by strake

Closes #3727

2019-12-08 15:18 UTC, gallais commented
Can we also get a failing test showing that the name of the imported module
is not in scope? This was, after all, the motivation of the original issue.
Something like

```
open import Agda.Builtin.Nat as _

_ : Nat                   -- this should be fine: the content was imported
_ = Agda.Builtin.Nat.zero -- this should lead to a scope error
```

2019-12-09 07:06 UTC, strake commented
@gallais Done

2019-12-09 10:38 UTC, andreasabel requested changes
Very good solution!
As a small change request, please move the failing test case into `test/Fail`.

2019-12-09 10:38 UTC, andreasabel commented on test/Compiler/simple/AnonymousImport-1.agda
> +module AnonymousImport-1 where
The place for a test case that should fail in the scope or type checker would be `test/Fail` (rather than `test/Compiler/simple`).

2019-12-09 15:25 UTC, strake commented
@andreasabel Done

2019-12-10 10:10 UTC, gallais commented
Similarly the successful one should probably be in test/Succeed

2019-12-15 19:46 UTC, strake commented
@gallais Done

The CI failure seems unrelated; can someone confirm or deny? (It [passed](https://travis-ci.org/strake/agda/builds/625162039) on my branch.)

2019-12-15 20:52 UTC, gallais approved these changes

2019-12-23 13:19 UTC, merged

2019-12-23 13:19 UTC, gallais commented
Thank you!