[doc] added infix notation for constructors
agda/agda pull request #4436
Opened 2020-02-10 13:22 UTC by pnlph

See issue #4426

2020-02-10 15:01 UTC, UlfNorell approved these changes

2020-02-10 19:44 UTC, andreasabel requested changes
Thanks for the contribution.
Got a few suggestions for improvement.

2020-02-10 19:44 UTC, andreasabel commented on doc/user-manual/language/mixfix-operators.lagda.rst
> +parts if we separate them with one or more underscore characters ``_``, and the
> if we separate them with one or more underscore characters
No, only with exactly one underscore.  Better formulation:
> if we separate them with underscore characters

2020-02-10 19:44 UTC, andreasabel commented on doc/user-manual/language/mixfix-operators.lagda.rst
> +
While you are at it, you could include _sections_. All alternatives are:
```agda
if x then y else z
(if_then y else z) x
(if x then_else z) y
if x then y else_ z
if x then_else_ y z
if_then y else_ x z
(if_then_else z) x y
if_then_else_ x y z
```
Please add some of the section alternatives (leaving some underscores).

2020-02-10 19:44 UTC, andreasabel commented on doc/user-manual/language/mixfix-operators.lagda.rst
> +    _::_ : A -> List A -> List A
Please use the unicode arrow here (and preferable the unicode ::).

2020-02-11 12:24 UTC, andreasabel approved these changes
Thanks for fixing!

2020-02-11 12:25 UTC, merged