[re #4461] Better implementation of subLevel.
agda/agda pull request #4462
Opened 2020-02-20 18:47 UTC by sattlerc

The fix 10bb7c1 to #4461 depends on too many special cases. Here is a more general implemention of `subLevel`. For example, `subLevel 2 (Max 1 [PlusLevel 2 x])` returned `Nothing` before, but returns `Max 0 [PlusLevel 0 x]` now.

2020-02-20 20:27 UTC, sattlerc commented
There could be some hidden invariants of the form 'if the closed level is subsumed by any plus levels, it is zero' that are not preserved by this implementation.

2020-02-20 21:15 UTC, gallais commented
I think this is indeed the intent, cf. the [original commit](https://github.com/agda/agda/commit/4d487559af821c3a7985c1592f6ff5b1afb0d600#diff-9c867e1712f6243860b313d3852f71cdR1464)

2020-02-20 21:24 UTC, jespercockx approved these changes
I approve of this change. I don't think it makes a functional difference (see comment by @gallais) but it's still much easier to see that this one is correct.

2020-02-20 21:28 UTC, jespercockx commented
Wait, I think there's something wrong with the new implementation: if the constant is `0` then it should not matter whether it is bigger than the constant we want to subtract. So it seems we do need at least one special case.

2020-02-20 21:30 UTC, jespercockx requested changes
Please ensure that `subLevel 1 (Max 0 (Plus 1 l))` returns `Just (Max 0 (Plus 0 l))`, I don't think the current implementation does.

As a sidenote: this might be a good candidate function for having some internal test cases.

2020-02-20 22:50 UTC, sattlerc commented
> Please ensure that `subLevel 1 (Max 0 (Plus 1 l))` returns `Just (Max 0 (Plus 0 l))`, I don't think the current implementation does.

I think it does.

However, it does not preserve the invariant that the level be in 'canonical form' as defined in `levelMax`. For example, `subLevel 1 (Max 0 (Plus 2 l))` returns `Max 1 (Plus 1 l)` instead of `Max 0 (Plus 1 l)`. I think now that the intent was that `subLevel` should operate on canonical forms.

Here is a modified version that operators on canonical forms like the original.
```haskell
-- | Given a constant @n@ and a level @l@, find the level @l'@ such
--   that @l = n + l'@ (or Nothing if there is no such level).
subLevel :: Integer -> Level -> Maybe Level
subLevel n (Max m ls) = Max <$> m' <*> traverse subPlus ls
  where
    m' :: Maybe Integer
    m' | m == 0, not (null ls) = Just 0
       | otherwise             = sub m

    -- General purpose function.
    nonNeg :: Integer -> Maybe Integer
    nonNeg j | j >= 0 = Just j
             | otherwise = Nothing

    sub :: Integer -> Maybe Integer
    sub = nonNeg . subtract n

    subPlus :: PlusLevel -> Maybe PlusLevel
    subPlus (Plus j l) = Plus <$> sub j <*> Just l
```

2020-02-21 08:48 UTC, merged

2020-02-21 08:49 UTC, jespercockx commented
Thanks!