update Cabal installation instruction
agda/agda pull request #4473
Opened 2020-02-23 09:49 UTC by neosimsim

Since Cabal 3.0 `v2-*` commands have become the default and packages are
no longer globally installed by default, see

https://www.haskell.org/cabal/users-guide/nix-local-build-overview.html

This requires required libraries (e.g. ieee754) to be registered
manually in the GHC environment.

2020-02-23 10:00 UTC, neosimsim commented
I'm not sure if the old instructions should be kept. I use Cabal 3.0 exclusively for a while now, but I'm not sure if that's the case for everyone.

2020-02-23 14:15 UTC, nad commented
We still support GHC 8.0.2, and I don't think we should force users to upgrade cabal-install.

2020-02-23 18:08 UTC, neosimsim commented
Okay fine, makes sense. Would it be useful to split the instruction into to parts, then? One for Cabal <2.4 and one for Cabal >=2.4? I would be glad to do so.

The thing is, that it took me a while to get Agda working with Cabal 3.0.0.0. After trying stack and nix
I finally found a way do to it with Cabal. Maybe others find it helpful, too.

2020-03-01 12:09 UTC, jrp2014 commented
This one bit me too.  Out of the box, `make` compiles OK, provided that you fiddle around installing the right `icu` library (which on a Mac with `brew` requires some path fiddling) but `make test` fails in an ugly way, missing the `ieee754` library.  It would be good to fix this in the `Makefile` if that didn't break `stack`

2020-03-02 13:36 UTC, asr requested changes

2020-03-02 13:36 UTC, asr commented on doc/user-manual/getting-started/installation.rst
> +  Actually it is not necessary to register the Agda libraries,
libraries -> library

2020-03-02 13:48 UTC, asr commented
> This one bit me too. Out of the box, `make` compiles OK, provided that you fiddle around installing the right `icu` library (which on a Mac with `brew` requires some path fiddling) but `make test` fails in an ugly way, missing the `ieee754` library. It would be good to fix this in the `Makefile` if that didn't break `stack`.
> 
> Incidentally, the interaction (and perhaps other) test fail, when using cabal, because the output contains extra lines like:
> 
> ```
> Loaded package environment from /Users/user/.ghc/x86_64-darwin-8.8.2/environments/default
> ```

@jrp2014, please uses #4216 for reporting problems in the `Makefile` with recent versions of `cabal-install`.

2020-03-06 23:40 UTC, merged

2020-03-06 23:40 UTC, asr commented
Thanks!

2020-03-07 09:13 UTC, neosimsim commented
@asr Thanks for fixing the typo.