Bump aeson version lower bound
agda/agda pull request #4499
Opened 2020-03-05 07:10 UTC by zliu41

0.11.3.0 does not have `toJSONList` used by Agda.Interaction.JSON.
1.1.2.0 is the version in lts-9.21.

2020-03-05 14:18 UTC, asr requested changes
This PR must be tested with all the supported versions of GHC. Please add the text "complete tests" to the commit message so the Travis CI uses them.

2020-03-06 02:28 UTC, zliu41 commented
> This PR must be tested with all the supported versions of GHC. Please add the text "complete tests" to the commit message so the Travis CI uses them.

Done. The CI error seems unrelated. 8.6.5 certainly builds fine on my machine.

2020-03-06 03:04 UTC, L-TChen approved these changes

2020-03-06 03:06 UTC, banacorn approved these changes

2020-03-06 13:08 UTC, asr approved these changes

2020-03-06 13:08 UTC, merged

2020-03-06 13:09 UTC, asr commented
Thanks!