Issue4638
agda/agda pull request #4670
Opened 2020-05-25 14:54 UTC by Saizan

PR for #4638

2020-05-26 16:11 UTC, andreasabel requested changes
Do we need to erase erased clauses during compilation or is this happening already?

2020-05-26 16:11 UTC, andreasabel commented on src/full/Agda/TypeChecking/Coverage.hs
> +            Quantity0{} -> return (q <>)
Picky comment: Shouldn't this rather return `mapQuantity (q <>)` and then below use just `f` instead of `mapQuantity f`?

2020-05-27 09:15 UTC, Saizan commented
> Do we need to erase erased clauses during compilation or is this happening already?

That's a good question, is there a good way to setup a test for that?

Meanwhile I'll try to look at the compiler code.

2020-05-28 19:39 UTC, andreasabel approved these changes

2020-06-03 11:18 UTC, nad commented
A non-trivial test case that currently fails:
```agda
{-# OPTIONS --cubical #-}

module Erased-constructor-test where

open import Agda.Builtin.Char
open import Agda.Builtin.String
open import Equality.Path
import Equality.Propositional as EP
open import IO-monad
open import Prelude
open import String

open import Bag-equivalence equality-with-J as BE using (_∼[_]_; bag)
open import List equality-with-J as L
open import Monad EP.equality-with-J
open import H-level.Closure equality-with-J
open import Quotient.Erased equality-with-paths as Q

len : List Char /ᴱ _∼[ bag ]_ → ℕ
len = Q.rec λ where
  .[]ʳ                   → length
  .[]-respects-relationʳ → BE.length-cong
  .is-setʳ               → ℕ-set

total-len : List String → ℕ
total-len = sum ∘ L.map (len ∘ [_] ∘ primStringToList)

main = do
  args ← getArgs
  putStrLn (prettyℕ (total-len args))
```
To test:
```
git clone --single-branch --branch erased-constructors https://github.com/nad/equality.git
```
Save `Erased-constructor-test.agda` in `equality`.
```
cd equality
agda -i. --compile Erased-constructor-test.agda 
```
Currently Agda complains:
```
An internal error has occurred. Please report this as a bug.
Location of the error: src/full/Agda/Compiler/MAlonzo/Primitives.hs:138
```
I guess this is expected, because I have not marked all cubical code as erased. However, I think that all cubical code reachable from `main` is marked as erased.

2020-06-03 11:27 UTC, Saizan commented
You should just get a `NotImplemented` or runtime error if some cubical primitive ends up in the compiled code.

The impossible is Malonzo not even being able to get at the builtin name. I'll test on my end.

2020-06-03 11:31 UTC, nad commented
Before this is released we should try to make sure that this kind of code does not lead to run-time errors.

2020-06-05 10:46 UTC, nad commented
I fixed some problems related to #4727 by manually giving some implicit arguments (and force-pushed the changes). Now I get the following error:
```
MAlonzo/Code/HZ45Zlevel/Truncation/Propositional.hs:214:7: error:
    • The constructor ‘C1720’ should have 2 arguments, but has been given 3
```
The eliminator for the propositional truncation operator with a *non-erased* higher constructor is not compiled correctly. Perhaps it makes sense to (optionally) only compile code that can be reached from `main`.

I'll try to do some manual pruning.

2020-06-05 10:54 UTC, nad commented
```
$ ./Erased-constructor-test It works
7
```

2020-06-05 10:57 UTC, nad commented
I've pushed a commit with the manually pruned code to the branch, so that you can also test this.

2020-10-16 08:52 UTC, Saizan commented
@nad did you say you had merged master into this?

2020-10-16 09:53 UTC, nad commented
I've pushed some merge commits now.

2020-11-06 23:29 UTC, nad commented
One compiler test (#2918) fails.

2020-12-01 10:51 UTC, nad commented
> Before this is released we should try to make sure that this kind of code does not lead to run-time errors.

I've made the backends more picky. Now they refuse to compile higher inductive types and (at least some) cubical primitives.

2020-12-01 15:20 UTC, merged