[ interaction ] Constraints overlapping metas not highlighted
agda/agda pull request #4742
Opened 2020-06-09 11:34 UTC by Saizan

If an unsolved constraint range overlaps an unsolved or interaction
meta range it does not generate highlighting in the interaction mode.

2020-06-09 21:49 UTC, andreasabel requested changes
I haven't tested this PR.  Looks good. The only thing I found from just reading it through is the complexity issue with `overlappings`.

2020-06-09 21:49 UTC, andreasabel commented on src/full/Agda/Interaction/Highlighting/Range.hs
> +overlappings (Ranges r1s) (Ranges r2s) = or [ overlapping r1 r2 | r1 <- r1s, r2 <- r2s ]
Since the ranges inside `Ranges` are ordered ascendingly, there should be a linear implementation rather than a quadratic one.

2020-06-10 08:49 UTC, andreasabel commented
UPDATE: The general pattern behind overlappings seems to be the question of whether one can merge two lists sorted by a strict ordering < into one such. If this is not possible, there is an overlapping. Thus, maybe it is best to implement a utility function for lists in Agda.Utils.List:
```haskell
mergeStrictlyOrderedBy :: (a -> a -> Bool) -> [a] -> [a] -> Maybe [a]
mergeStrictlyOrderedBy (<) = loop where
  loop [] ys = Just ys
  loop xs [] = Just xs
  loop (x:xs) (y:ys)
    | x < y = (x:) <$> loop xs (y:ys)
    | y < x = (y:) <$> loop (x:xs) ys
    | otherwise = Nothing
```
and then
```haskell
isLeftOf :: Range -> Range -> Bool
isLeftOf r1 r2 = to r1 <= from r2

overlapping r1 r2 = (not $ r1 `isLeftOf` r2) && (not $ r2 `isLeftOf` r1)

overlappings (Ranges r1s) (Ranges r2s) =
  isNothing $ mergeStrictlyOrderedBy isLeftOf r1s r2s
```

2020-06-10 11:29 UTC, Saizan commented
I replaced `overlappings` with the `mergeStrictlyOrderedBy` implementation, using the older impl. as spec for the tests, which do pass, so I will merge.

2020-06-10 11:31 UTC, merged