Recent ubuntu for build
agda/agda pull request #4753
Opened 2020-06-16 01:58 UTC by JacquesCarette

Use `ubuntu-latest` instead of `ubuntu-16.04` for the workflows. Everything seemed to work fine.

2020-06-16 15:34 UTC, asr requested changes

2020-06-16 15:34 UTC, asr commented on .github/workflows/cabal.yml
> +    runs-on: ubuntu-latest
Please use Ubuntu version instead of `latest`.

2020-06-16 15:34 UTC, asr commented on .github/workflows/haddock.yml
> +    runs-on: ubuntu-latest
Please use Ubuntu version instead of `latest`.

2020-06-16 15:34 UTC, asr commented on .github/workflows/nightly.yml
> +    runs-on: ubuntu-latest
Please use Ubuntu version instead of `latest`.

2020-06-16 15:34 UTC, asr commented on .github/workflows/user_manual.yml
> +    runs-on: ubuntu-latest
Please use Ubuntu version instead of `latest`.

2020-06-16 15:34 UTC, asr commented on .github/workflows/whitespace.yml
> +    runs-on: ubuntu-latest
Please use Ubuntu version instead of `latest`.

2020-06-16 15:42 UTC, asr commented
After googling the error in 8.0.2 it seems the missing package is `libicu-dev`.

2020-06-16 15:51 UTC, jespercockx commented
Most people I know (including myself) are only using LTS releases of Ubuntu. So I do not think we should run the test on one of the in-between versions. Instead, we should wait until there is proper support for 20.04 and then upgrade to that. (16.04 is still supported for 3 years so there is no rush.)

2020-06-16 15:59 UTC, asr commented
I also only use LTS releases (16.04) and I agree there is no rush, but note the 18.04 is a LTS release.

2020-06-16 16:10 UTC, jespercockx commented
Oh my bad, you're right. It *would* make sense to upgrade to 18.04.

2020-06-16 16:24 UTC, JacquesCarette commented
Note that **only** LTU releases are ever supported on the build infrastructure. So `-latest` means 18.04 now, and would move to 20.04 'later'.  But I can definitely change things to be explicit about the version.

Yes, I had figured out that the issue is text-icu (which was already a 'problem' on both Mac and Windows), I was still investigating what the best way was to make sure that package was included. I'm quite new at YAML build files, so any advice on that would be appreciated.

2020-06-16 17:04 UTC, asr reviewed
Thanks for using an explicit version.

2020-06-17 05:12 UTC, asr approved these changes

2020-06-17 13:33 UTC, asr commented
I didn't realise the stage of the PR (draft) and I reviewed it. Also, I accidentally changed its stage (draft -> ready for review).

2020-06-17 13:35 UTC, JacquesCarette commented
No problem - as it turns out, I was going to check that everything is indeed ok, and mark it ready for review!

2020-06-17 13:53 UTC, asr commented
Good! Can you squash and merge?

2020-06-17 13:58 UTC, merged

2020-06-17 13:59 UTC, JacquesCarette commented
Done!

2020-06-17 14:32 UTC, JacquesCarette commented
Note that the merge build failed. The Linux ones because:
```
E: Failed to fetch https://storage.googleapis.com/bazel-apt/dists/stable/jdk1.8/binary-amd64/Packages.gz  File has unexpected size (3470 != 3690). Mirror sync in progress? [IP: 172.217.9.208 443]
```
which is outside of our control, so that looks like a fluke.

The Haddock one is stranger:
```
<command line>: libicuuc.so.55: cannot open shared object file: No such file or directory
```
as that is a symptom that this used a cached version. But the run of the last check-in worked for Haddock.  I'll have to investigate.

2020-06-17 14:59 UTC, andreasabel commented
> But the run of the last check-in worked for Haddock. I'll have to investigate.

Yeah, weird, the Haddock action is broken on master but passed on your PR.

2020-06-17 17:27 UTC, JacquesCarette commented
Note that I have a bunch of urgent things to do, so won't be able to get back to this until evening (in UTC-4); if the Haddock action being broken is hampering others, feel free to take a look!  I'm pretty sure the problem is related to a cached version of GHC that hard-codes which libraries to use.