`[ci skip]` and `[skip ci]` instructions for Github Workflows
agda/agda pull request #4791
Opened 2020-07-05 10:20 UTC by EdNutting

Resolves #4729 as per agreed solution. The presence of `[ci skip]` or `[skip ci]` in the head commit of a push will cause Github Workflows to be skipped. This matches the behaviour of Travis.

Note: If someone wants to skip Travis but not Github Workflows, they should include `[skip travis]` in the head commit message, [as per the documentation on this page](https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build).

2020-07-05 11:00 UTC, gallais approved these changes
Thanks! :heart:

2020-07-05 22:45 UTC, asr requested changes
Please add documentation to the section [Testing with Travis CI and GitHub Actions](https://github.com/agda/agda/blob/2a933b99bf12dbc770b5982b4fb38993ecad8aac/HACKING.md#testing-with-travis-ci-and-github-actions) in `HACKING.md`.

2020-07-06 02:32 UTC, L-TChen reviewed
These CI commands are for local use only and they are better removed before merging into `master`.

So, I think it is worthwhile to explain this in [HACKING.md](https://github.com/agda/agda/blob/master/HACKING.md) altogether. 

Otherwise, it looks good to me.

2020-07-06 12:41 UTC, asr commented
While working in https://github.com/agda/agda/issues/4792 I'm in the (no common) situation where I want to skip the GitHub workflows but running Travis. What about to add `[skip github]` and `[github skip]` for this case?

2020-07-19 21:58 UTC, rwe commented
As a minor suggestion — and I'm not sure about Travis — but it can be nice to additionally allow CI-skip stuff to be flagged by a label or the PR title. That way for work-in-progress PRs, it doesn't have to be included in each individual commit message.

[According to the docs](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#webhook-payload-example-29), the relevant event attribute would be `github.event.pull_request.title` or `.labels`.

2020-07-20 16:13 UTC, EdNutting commented
@rwe As per the issue associated with this PR, there is disagreement over that kind of workflow. Please continue the conversation about that on the ticket - probably worth reposting your comment there for continued discussion. I'd like to get this PR in soon just to solve the smaller original problem :)

2020-07-20 18:26 UTC, rwe commented
@EdNutting Thanks for pointing that out, and I agree. The suggestion was supplementary, not meant to impede this PR as-is.

2020-07-23 05:10 UTC, asr requested changes
In `Hacking.md` replace `Github` by `GitHub` and `Travis workflows` by `Travis jobs`.

2020-07-23 13:05 UTC, asr approved these changes

2020-07-23 13:37 UTC, L-TChen approved these changes

2020-07-23 22:43 UTC, rwe commented
Ok, `master` is now passing. I'm trying to restart the Travis build, but hitting "Restart Build" does not seem to update the base branch: it's still building the older merge commit. Any tips? Or is manually updating the base branch here (which will also trigger stack/cabal/etc) the only option?

2020-07-23 23:34 UTC, merged

2020-07-23 23:36 UTC, rwe commented
All checks passed after restarting the build. I've merged this in because there were no changes in this branch since review approval and there were no accompanying source code changes.