Add agda mode comentary
agda/agda pull request #4921
Opened 2020-09-14 08:30 UTC by jappeace

This is so that the melpa page has more information
than just 'agda-mode'.

This was requested by the melpa maintainers:

- https://github.com/melpa/melpa/pull/7080

Feel free to suggest improvements on the written commentary, I just skimmed the source to see what it does.

2020-09-14 08:33 UTC, gallais commented
I don't know what "introspection" means but I would most
certainly highlight:

* goal-driven development
* interactive case-splitting
* proof search

2020-09-16 12:06 UTC, andreasabel commented
Maybe _interaction_, not _introspection_?

2020-09-16 16:38 UTC, andreasabel requested changes

2020-09-16 16:38 UTC, andreasabel commented on src/data/emacs-mode/agda2-mode.el
> +;; - introspection
Please fix this following e.g. suggestions by @gallais.

2020-09-21 16:41 UTC, andreasabel commented on src/data/emacs-mode/agda2-mode.el
> +;; - introspection
Thx.

2020-09-21 16:42 UTC, merged

2020-09-21 16:42 UTC, andreasabel commented
Thanks, @jappeace !