[ fix #2858 ] Interleaving mutually-defined functions and datatypes
agda/agda pull request #5001
Opened 2020-10-22 15:25 UTC by gallais

Prototypical example: a universe closed under `Nat` and `Sigma`
defined by IR. The interleaving mutual block allows us to consider
each constructor & its semantics in turn.

```agda
open import Agda.Builtin.Nat
open import Agda.Builtin.Sigma

infix mutual

  data Code : Set
  ⟦_⟧ : Code → Set

  constructor `Nat : Code
  ⟦ `Nat ⟧ = Nat

  constructor `Σ : (r : Code) → (⟦ r ⟧ → Code) → Code
  ⟦ `Σ A B ⟧ = Σ ⟦ A ⟧ λ a → ⟦ B a ⟧
```

2020-10-22 17:40 UTC, gallais commented
I am getting some internal errors during interactive development.
Looks like I'll need to turn more `__IMPOSSIBLE__` into warnings.

2020-10-25 19:57 UTC, andreasabel requested changes
This is the 3rd flavor of mutual blocks, maybe we should just number the different types:
- `mutual`: old-style mutual blocks
- `mutual-i`: new-style mutual blocks.  No keyword so far, but it has been suggested to add a keyword for these, which would be optional (at least for a long deprecation phase). 
- `mutual-ii`: This "`infix mutual`" variant.
- ... (the next even more powerful variant)

Maybe arabic `mutual1`, `mutual2` or their subscript variant looks better.

2020-10-25 19:57 UTC, andreasabel commented on src/full/Agda/Interaction/Options/Warnings.hs
> +  InvalidConstructorBlock_         -> "No `constructor' blocks outside of `infix mutual' blocks."
`infix mutual` is only a placeholder for a keyword determined by bikeshedding, I suppose?

2020-10-25 20:10 UTC, gallais commented on src/full/Agda/Syntax/Concrete/Definitions.hs
> +      let dec k (InfixData (i, d@(NiceDataSig _ acc abs pc uc _ pars _)) ds) =
TODO: move these transformations next to the `InfixData` / `InfixFun` introduction site.

2020-10-26 13:28 UTC, andreasabel approved these changes
Not sure it makes sense for me to try a proper review...  It is a new feature, so it will be tried in practice.

Where did the discussion take place? (Link!)

2020-10-26 13:47 UTC, gallais commented
Discussion took place on Zoom during the last wrap up meeting & was
summarised on zulip: https://agda.zulipchat.com/#narrow/stream/257010-aim-xxxiii/topic/Bikeshedding.20.235001

2020-10-27 14:27 UTC, merged