[ makefile, fix #5500 ] Do not add any additional suffix to `quicker-install-bin` and etc.
agda/agda pull request #5511
Opened 2021-08-17 18:02 UTC by L-TChen

It should fix the issue mentioned in #5500.

2021-08-17 19:31 UTC, andreasabel requested changes

2021-08-17 19:31 UTC, andreasabel commented on Makefile
> +	$(MAKE) copy-bins-with-suffix-quicker STACK_BUILD_DIR=$(FAST_STACK_BUILD_DIR)
Shouldn't the suffix be `-fast` here?

2021-08-18 07:09 UTC, L-TChen commented on Makefile
> +	$(MAKE) copy-bins-with-suffix-quicker STACK_BUILD_DIR=$(FAST_STACK_BUILD_DIR)
Typo. Done.

2021-08-18 08:14 UTC, andreasabel approved these changes

2021-08-18 08:16 UTC, merged

2021-08-18 08:16 UTC, andreasabel commented
Thanks!