Fix #5610 for real now
agda/agda pull request #5615
Opened 2021-10-25 11:37 UTC by jespercockx

Re-insert necessary checks on types of built-in coinduction primitives

2021-10-25 12:19 UTC, andreasabel requested changes
Thanks for fixing.

Please also add the rest of my counterexample (see specific comment above).

2021-10-25 12:19 UTC, andreasabel commented on test/Fail/BuiltinSharpBadType.agda
> +
Even though this is the MWE, keeping the rest (till the proof of False) is nice to preserve, also to show the importance of checking the given types.  
Remark: the reason why you can get False with these built-ins is that \infinity is assumed to be strictly-positive in the positivity checker (even guarding positive).  So making `∞ A` isomorphic to `A → ⊥` will be contradictory to this assumption.

2021-10-25 15:39 UTC, andreasabel commented on test/Fail/BuiltinSharpBadType.agda
> +
I intentionally put the comment on the `BuiltinSharpBadType` file because this is the one that can be extended to my example, while keeping the sharp-flat order.  Putting it into `BuiltinFlatBadType` also works if flat is bound before sharp.  Atm, there is a problem with the type of sharp in `BuiltinFlatBadType`...

2021-11-03 08:15 UTC, andreasabel requested changes
Ping @jespercockx

2021-11-03 11:57 UTC, jespercockx commented
Sorry, I lost track of this one. I pushed the change to the test cases, I hope everything's fine now?

2021-11-03 16:39 UTC, andreasabel approved these changes
Excellent!

2021-11-03 16:41 UTC, merged