#5731
agda/agda pull request #5756
Opened 2022-01-25 20:32 UTC by nad

Changes related to issue #5731.

2022-02-01 08:14 UTC, andreasabel requested changes
Nice work!

Could you please put an summary/description of the most salient features of this PR in at the top of the "Conversation" thread?

Also, the distinction between local/external metas should be documented in such a summary somewhere in the codebase, maybe in `TC.Monad.Base` where the meta-store is introduced.

2022-02-01 08:14 UTC, andreasabel commented on src/full/Agda/TypeChecking/Monad/Base.hs
> +data RemoteMetaVariable = RemoteMetaVariable
"remote" sound to me like a metavariable accessible via a URI.  (Cf. _remote procedure call_).
How about "external"?

2022-02-01 08:14 UTC, andreasabel commented on src/full/Agda/TypeChecking/Monad/MetaVars.hs
> +  created :: Lens' LocalMetaStore TCState -> MetaId -> m LocalMetaStore
I'd find it more natural to pass the `LocalMetaStore` to this auxiliary function rather than the lens.  This would mean a duplication of `useTC`, but it would be a more meaningful factor.

2022-02-01 08:14 UTC, andreasabel commented on src/full/Agda/TypeChecking/Monad/MetaVars.hs
> +  lkup = MapS.lookup m
Please inline `lkup` for sake of readability.

2022-02-01 08:14 UTC, andreasabel commented on src/full/Agda/TypeChecking/Monad/MetaVars.hs
> +lookupMeta ::
Breaking a long type signature as follows:
```haskell
lookupMeta 
  :: ReadTCState m 
  => MetaId 
  -> m (Maybe (Either RemoteMetaVariable MetaVariable))
```
seems to make more sense as then haddockumentation of arguments can be attached on the right, or after each line.

2022-02-01 08:14 UTC, andreasabel commented on src/full/Agda/TypeChecking/Monad/MetaVars.hs
> +  mv <- lookupLocalMeta' m
Why not?
```haskell
  lookupLocalMeta' m >>= \case
```
Saves binding `mv` (and shadowing it then).

2022-02-01 08:14 UTC, andreasabel commented on src/full/Agda/TypeChecking/Monad/MetaVars.hs
> +  mi <- lookupMeta m
`>>= \case`

2022-02-01 08:14 UTC, andreasabel commented on src/full/Agda/TypeChecking/Monad/MetaVars.hs
> +getMetaPriority ::
Document that this only looks in the local metas.

2022-02-01 08:14 UTC, andreasabel commented on src/full/Agda/TypeChecking/Monad/MetaVars.hs
> +  j <- lookupMetaJudgement m
`lookupMetaJudgement m <&> \case`

2022-02-01 08:14 UTC, andreasabel commented on src/full/Agda/TypeChecking/Monad/MetaVars.hs
> +  inst <- lookupMetaInstantiation m
`lookupMetaInstantiation m <&> \case`

2022-02-01 08:14 UTC, andreasabel commented on src/full/Agda/TypeChecking/Monad/MetaVars.hs
> +  unfreezeMeta x = unlessM (($ x) <$> isRemoteMeta) $ do
`isRemoteMeta <*> pure x`

2022-02-01 08:14 UTC, andreasabel commented on src/full/Agda/TypeChecking/Reduce.hs
> +  inst <- lookupMetaInstantiation m
`\case`

2022-02-01 08:14 UTC, andreasabel commented on src/full/Agda/TypeChecking/Reduce.hs
> +  pred <- redPred <$> askR
```haskell
caseMaybeM (redPred <$> askR) holds $ \ p ->
  ifM (p m) holds doesNotHold
```

2022-02-01 12:16 UTC, nad commented on src/full/Agda/TypeChecking/Monad/MetaVars.hs
> +getMetaPriority ::
There are more examples of undocumented procedures with changed semantics, but I can fix this one.

2022-02-01 12:17 UTC, nad commented
> Could you please put an summary/description of the most salient features of this PR in at the top of the "Conversation" thread?

I put a [summary](https://github.com/agda/agda/issues/5731#issuecomment-1026283941) in the thread of issue #5731.

> Also, the distinction between local/external metas should be documented in such a summary somewhere in the codebase, maybe in `TC.Monad.Base` where the meta-store is introduced.

It is documented:

https://github.com/agda/agda/blob/0e80e2b75490d272724db07c80efe865ae89d6eb/src/full/Agda/TypeChecking/Monad/Base.hs#L1476-L1482

However, perhaps the documentation could be improved:

https://github.com/agda/agda/blob/0e80e2b75490d272724db07c80efe865ae89d6eb/src/full/Agda/TypeChecking/Monad/Base.hs#L985-L986

I'll fix this.

Most of your other feedback is related to the style of the code. Thanks for your effort, but I don't want to spend time on bike-shedding. I asked you to review my changes because I removed some dead code (you have in the past objected to this), and because I changed the `size-solver` program.

2022-02-01 17:19 UTC, andreasabel requested changes
- Ok to delete the old size-solver.
- The errors of the size solver should be printable in the `size-solver` client.
- Please place a commentary on the new local/remote meta distinction in the code, explaining purpose, design decisions, and potential caveats.

2022-02-01 17:19 UTC, andreasabel commented on src/size-solver/test/fail.test
> +Error
The error message is lost by the refactoring.  Should be refactored in a way that does not make the error message unusable in the context of `size-solver`.

2022-02-01 17:19 UTC, andreasabel commented on src/full/Agda/TypeChecking/SizedTypes/Syntax.hs
> +type Error = TCM Doc
Mmh, this does not seem to work in the context of `size-solver`.

I thought about alternatives back and forth, and the best seems to be a structured `Error` type with one constructor for each error.  Then, printing can be handled by the client, either using `PrettyTCM` or something simpler.

2022-02-01 17:25 UTC, andreasabel commented
> > Could you please put an summary/description of the most salient features of this PR in at the top of the "Conversation" thread?
> 
> I put a [summary](https://github.com/agda/agda/issues/5731#issuecomment-1026283941) in the thread of issue #5731.

This is very informative, I'd like to see this also in the codebase.

> Most of your other feedback is related to the style of the code. Thanks for your effort, but I don't want to spend time on bike-shedding. I asked you to review my changes because I removed some dead code (you have in the past objected to this), and because I changed the `size-solver` program.

You could have stated which part of the code you want the feedback on.
(See my second review for this feedback.)

2022-02-01 18:32 UTC, nad commented
> * The errors of the size solver should be printable in the `size-solver` client.

Why do we support this program? I already wasted some time on making it compile, and I do not plan to do anything else.

> * Please place a commentary on the new local/remote meta distinction in the code, explaining purpose, design decisions, and potential caveats.

Does the following sound reasonable (as part of the documentation of `RemoteMetaVariable`)?

```haskell
-- Remote meta-variables are meta-variables originating in other
-- modules. These meta-variables are always instantiated. We do not
-- retain all the information about a local meta-variable when
-- creating an interface:
--
-- * The 'mvPriority' field is not needed, because the meta-variable
--   cannot be instantiated.
-- * The 'mvFrozen' field is not needed, because there is no point in
--   freezing instantiated meta-variables.
-- * The 'mvListeners' field is not needed, because no meta-variable
--   should be listening to this one.
-- * The 'mvTwin' field is not needed, because the meta-variable has
--   already been instantiated.
-- * The 'mvPermutation' is currently removed, but could be retained
--   if it turns out to be useful for something.
-- * The only part of the 'mvInfo' field that is kept is the
--   'miModality' field. The 'miMetaOccursCheck' and 'miGeneralizable'
--   fields are omitted, because the meta-variable has already been
--   instantiated. The 'Range' that is part of the 'miClosRange' field
--   and the 'miNameSuggestion' field are omitted because instantiated
--   meta-variables are typically not presented to users. Finally the
--   'Closure' part of the 'miClosRange' field is omitted because it
--   can be large (at least if we ignore potential sharing).
```
This comment could quickly become out of date, but perhaps that is fine.

2022-02-02 10:57 UTC, nad commented
I added the comment above.

I also fixed the `size-solver` test case. However, I think we should consider removing this program from the repository, like we have with other programs.

2022-02-02 21:04 UTC, nad commented
I think this code is ready to be merged, except perhaps that there is only one (trivial) test case for `--save-metas`. All tests go through with `--save-metas` (except for one test case that includes the text `instantiating all meta variables` in the output), but I do not want to run all tests twice. Any suggestions?

2022-02-03 11:30 UTC, nad commented
One option would be to use `--save-metas` for the tests involving the standard library, to ensure that the tests involve lots of imported modules, as well as compilation. Does this sound reasonable?

2022-02-04 09:26 UTC, nad commented
> One option would be to use `--save-metas` for the tests involving the standard library, to ensure that the tests involve lots of imported modules, as well as compilation. Does this sound reasonable?

Maybe not, I think we should test the "default" way of using the standard library. I added the flag to some compiler test cases with imports.

2022-02-04 11:35 UTC, merged

2025-01-02 20:00 UTC, andreasabel commented on src/full/Agda/TypeChecking/Monad/Base.hs
> +  , redPred :: Maybe (MetaId -> ReduceM Bool)
This makes `ReduceM` a recursive type.
Pervers.