#5845: need to look inside blocked terms when computing constrained metas
agda/agda pull request #5847
Opened 2022-03-24 10:17 UTC by UlfNorell

fixes #5845

2022-03-24 11:50 UTC, andreasabel requested changes

2022-03-24 11:50 UTC, andreasabel commented on src/full/Agda/TypeChecking/Monad/MetaVars.hs
> +    loop :: Set MetaId -> [MetaId] -> Set MetaId -> TCM (Set MetaId)
Could you document the purpose of each of these three collections of metas?
That would help to grasp the logic.

2022-03-24 11:51 UTC, andreasabel commented
Thanks, with a request to enhance documentation.

2022-03-25 06:13 UTC, UlfNorell commented
The check is too strict and breaks the standard library. Some more thinking required to figure out what the right thing to do is.

2022-10-10 10:52 UTC, closed without merging