Added the copatterns with coinduction section to the user manual
agda/agda pull request #5918
Opened 2022-05-24 16:09 UTC by RemcoSchrijver

While I was experimenting with coinduction and copatterns for agda2hs, I came across [this gist](https://gist.github.com/puffnfresh/8960574) of  @puffnfresh which explained nicely how to use copatterns in combination with coinduction.

I felt I was missing this in the user manual of Agda, after reading the section on copatterns I myself still couldn't apply it on coinductive records. That's also the reason I came across this gist.

So I added the explanation of @puffnfresh and made it consistent with the other parts of the user manual. I didn't add the section of 'nats' because I wasn't sure how to explain that properly so that might still be of interest to include.

2022-05-24 18:48 UTC, andreasabel requested changes
Thanks for the contribution!

2022-05-24 18:48 UTC, andreasabel commented on doc/user-manual/language/copatterns.lagda.rst
> +
The option `--guardedness` which is necessary to process this example, should be mentioned in the text here.

2022-05-24 18:48 UTC, andreasabel commented on doc/user-manual/language/copatterns.lagda.rst
> +Copatterns with coinduction
This section does not fit here, because it cuts the `enum` example in the middle.  Please move it somewhere where it does not disrupt the narrative.  I suggest to the end of the file.

2022-05-24 18:51 UTC, andreasabel commented
Actually, I am coming to think whether these explanations are not already present in the section on coinduction: https://agda.readthedocs.io/en/latest/language/coinduction.html
Maybe just a link to the coinduction section from the copatterns section is missing?

2022-05-24 19:23 UTC, RemcoSchrijver commented
> Actually, I am coming to think whether these explanations are not already present in the section on coinduction: https://agda.readthedocs.io/en/latest/language/coinduction.html Maybe just a link to the coinduction section from the copatterns section is missing?

Yes it does talk about copatterns there indeed, but for a novice like me it wasn't immediately clear how I could translate those example to something like repeat. It feels to me like the functions like odd/even are somehow different to something that instantiate an stream like repeat.

So maybe it would be better to just add repeat as another example in the section on coinduction and then make a reference in copatterns to coinduction?

2022-05-25 07:44 UTC, andreasabel commented
> So maybe it would be better to just add repeat as another example in the section on coinduction and then make a reference in copatterns to coinduction?

Yes, that sounds right!

2022-05-25 09:29 UTC, RemcoSchrijver commented on doc/user-manual/language/copatterns.lagda.rst
> +If you are looking for information on how to use copatterns with
I am not sure if this is the correct place to reference the coinduction section, but it didn't feel like it could go anywhere else naturally either.

2022-05-27 13:29 UTC, andreasabel requested changes
Thanks for the update! 
This is good modulo some cosmetic changes.  (I could have done them myself, but you are the only person who has write access to this PR.  When opening a PR, you can give the maintainers write access by ticking the box `[ ] Allow maintainers...`)

2022-05-27 13:29 UTC, andreasabel commented on doc/user-manual/language/coinduction.lagda.rst
> +On top of creating fuctions that work on existing ``Stream``\s we can also use
fuctions --> functions

2022-05-27 13:29 UTC, andreasabel commented on doc/user-manual/language/coinduction.lagda.rst
> +:ref:`copatterns <copatterns>` to instantiate a ``Stream``\. Like the ``repeat``
The sentence starting with "Like the" does not have a verb.  
But you can join it to the previous sentence with `,`.

2022-05-27 13:29 UTC, andreasabel commented on doc/user-manual/language/copatterns.lagda.rst
> +If you are looking for information on how to use copatterns with
Yes, this is a god place.  Use the `.. note:` environment to make it stand out.

2022-05-27 13:40 UTC, RemcoSchrijver commented
Alright I implemented the small comsetic fixes, thank you for reviewing the PR!

2022-05-27 14:55 UTC, andreasabel commented on doc/user-manual/language/copatterns.lagda.rst
> +   Now consider the following record:
Er, the "Now consider" should not be part of the note.  Don't you need an empty line after the note?

2022-05-27 14:56 UTC, andreasabel requested changes
Please fix the note.

2022-05-27 14:57 UTC, andreasabel commented
Also, no trailing whitespace is allowed: https://github.com/agda/agda/runs/6627427305?check_suite_focus=true#step:8:5
> Run $HOME/.local/bin/fix-whitespace --check
> [ Violation detected ] doc/user-manual/language/coinduction.lagda.rst
> [ Violation detected ] doc/user-manual/language/copatterns.lagda.rst

Fix this by running `fix-whitespace` in the repo root.

2022-05-28 13:49 UTC, andreasabel approved these changes
I am fixing the remaining issues myself.

2022-05-28 13:58 UTC, andreasabel commented
Continued in 
- #5927

2022-05-28 13:58 UTC, closed without merging