Do not construct a full map when finding a single name
agda/agda pull request #6014
Opened 2022-08-09 22:16 UTC by SquidDev

Similar to #5998, when pretty printing lots of types or terms, we end up doing a large number of name lookups.

The current implementation calls `allNamesInScope`, which allocates a map of names to variables. As we're only looking up a single name, we can avoid this additional work, and only perform it on the variable we're searching for.

In my test project, this reduces the time taken in Scoping.InverseScopeLookup from 4.5s to 0.7s. As always, happy to benchmark other areas this might impact - wasn't sure what to try really!

2022-08-11 16:44 UTC, andreasabel requested changes
Thanks!
Approved modulo suggested cosmetic change.

2022-08-11 16:44 UTC, andreasabel commented on src/full/Agda/Syntax/Scope/Base.hs
> +  , name <- fromMaybe [] . Map.lookup n $ inNameSpace ns ]
`Map.findWithDefault [] n` is probably epsilon-better than `fromMaybe [] . Map.lookup n`.

2022-08-12 06:10 UTC, andreasabel approved these changes

2022-08-12 06:12 UTC, merged

2022-08-12 08:08 UTC, SquidDev commented
Thank you! :)