Fix documentation of `glue`.
agda/agda pull request #6103
Opened 2022-09-13 00:52 UTC by endobson

`glue` is not uncurried like `Glue`, yet the documentation had it as such.

2022-09-13 00:53 UTC, endobson commented
Link to current documuntation: https://github.com/agda/cubical/blob/0171924ce3d0c070d87a4792a0be888b0e8dd30d/Cubical/Core/Glue.agda#L36

I didn't want to document it using primGlue and so tried to get the result type correct.

2022-09-20 09:47 UTC, plt-amy commented
I'm not sure I like this change — the part of the documentation you're changing isn't meant to document the _literal_ primitives (that's the wall of code listings at the bottom of the file), but ratlher the interface we expect people to work with, for which the bundling of these parameters is largely immaterial — from a quick glance over the cubical library, nothing gives explicit arguments in these positions

2022-09-20 14:57 UTC, endobson commented
It isn't a well formed interface though, as there are unbound variables. The first explicit argument is documented as `PartialP φ T` and there is no `T` in scope. If you want to keep the implicit arguments documented as they are then this would need to change to ``PartialP φ (fst ∘ Te)` (or some other variation on that).

2022-09-30 11:56 UTC, andreasabel commented
How to resolve this PR?  @plt-amy , do you approve or request changes?  (Welcome to use the respective functionality of reviews.)

2022-09-30 16:15 UTC, plt-amy requested changes
If we're going to change the docs, we should make the types of `unglue` and `glue` match.

2022-09-30 16:15 UTC, plt-amy commented on doc/user-manual/language/cubical.lagda.rst
> +           {T : Partial φ (Set ℓ')} → {e : PartialP φ (λ o → T o ≃ A)}
Remove the arrow between the `{T : ...}` and `{e : ...}` binders, imo

2022-09-30 16:15 UTC, plt-amy commented on doc/user-manual/language/cubical.lagda.rst
>    unglue : ∀ {ℓ ℓ'} {A : Set ℓ} (φ : I) {Te : Partial φ (Σ[ T ∈ Set ℓ' ] T ≃ A)}
Uncurry the type of `unglue`, too.

2024-02-08 09:30 UTC, closed without merging