Docs for Cubical indexed types
agda/agda pull request #6232
Opened 2022-10-25 15:17 UTC by plt-amy

PR just because I've had bad times with reST before, and it would be embarrassing to mess that up on master.

2022-10-25 15:22 UTC, andreasabel commented
Rendering here: https://agda--6232.org.readthedocs.build/en/6232/language/cubical.html

2022-10-25 15:39 UTC, andreasabel reviewed
I committed some fixes directly.

2022-10-25 15:39 UTC, andreasabel commented on doc/user-manual/language/cubical.lagda.rst
> +  {-# OPTIONS --cubical -vtc.lhs.unify.inv:20 -WNoEquivWhenSplitting #-}
Do these extra options have any effect on the user-manual or its build?

2022-10-25 15:39 UTC, andreasabel commented on doc/user-manual/language/cubical.lagda.rst
> +  {-# OPTIONS --cubical -vtc.lhs.unify.inv:20 -WNoEquivWhenSplitting #-}
I removed them in my fixup, but feel free to restore them if that wasn't good.

2022-10-25 15:41 UTC, andreasabel commented
Er, I did the edit directly on github, and I think it screwed up when your commit came inbetween.

Let me repair this...

2022-10-25 15:42 UTC, plt-amy commented on doc/user-manual/language/cubical.lagda.rst
> +  {-# OPTIONS --cubical -vtc.lhs.unify.inv:20 -WNoEquivWhenSplitting #-}
Ah, thanks; they were just to help me figure out a minimal reproducer for the Setω transport case. (I think I'm going to write a pre-commit hook that looks through the diff and asks if I really meant to commit the verbosity flags....)

2022-10-25 15:46 UTC, andreasabel commented
Ok, fixed my commit.

2022-10-25 15:50 UTC, andreasabel approved these changes
From my side, this looks good, modulo I do not really understand Cubical enough to fully follow.  Maybe @mortberg wants to review...

2022-10-25 17:16 UTC, andreasabel commented
Looks like we rather need option `-WnoNoEquivWhenSplitting` (mmh, doubly-negated warning):
```
UserManual
    language-cubical:                              FAIL (0.89s)
                                                   Result did not match golden value.
                                                   Diff between actual and golden value:
...
+Could not generate equivalence when splitting on indexed family,
+the function will not compute on transports by a path.
+  Reason: UnsupportedYet Injectivity
+                           position:    0
+                           type:        Nat
+                           datatype:    Nat
+                           parameters: 
+                           indices:    
+                           constructor: suc
+when checking the definition of sucInjEq
```

2022-10-25 17:17 UTC, andreasabel commented
Let me fix the conflict I caused.

2022-10-25 17:26 UTC, andreasabel commented
I merged in `master`, we need to __SQUASH__ when merging this PR.

2022-10-26 10:16 UTC, andreasabel requested changes
I sat down again in a quieter moment and can say that I mostly follow this exposition.
I added some comments, some with a request to clarify the formulation.
Thanks for the docs!

2022-10-26 10:16 UTC, andreasabel commented on doc/user-manual/language/cubical.lagda.rst
> +generic is suboptimal when compared to the behaviour of similar
I don't see the transition of thought from "suboptimal" (negative) to the example that follows, where "we can investigate" (positive).  There is a gap in the argument, imo.

Can you reformulate to clarify?

2022-10-26 10:16 UTC, andreasabel commented on doc/user-manual/language/cubical.lagda.rst
> +compute when applied to transports.
Would this warrant an example?

2022-10-26 10:16 UTC, andreasabel commented on doc/user-manual/language/cubical.lagda.rst
> +compute when applied to transports.
Ah I see this comes later, but is interrupted by the `NoEquivWhenSplitting` discourse.

Please add the usual forward referencing.

2022-10-26 10:16 UTC, andreasabel commented on doc/user-manual/language/cubical.lagda.rst
> +compute on non-``reflEq`` paths:
Where will this hit me?  E.g. what lemma on `sucInjEq` will then fail to go through?

2022-10-26 10:16 UTC, andreasabel commented on doc/user-manual/language/cubical.lagda.rst
> +a partially-defined inverse to conclude it is injective:
I remember this trick from my apprentice years in type theory.

This seems to document a workaround.  Ok.  Might a good advice to users...

2022-10-28 06:45 UTC, andreasabel approved these changes
Great job, thanks!

2022-10-28 14:13 UTC, merged