Embrace git switch/restore
agda/agda pull request #6322
Opened 2022-11-14 01:32 UTC by favonia

Git 2.23 introduced git switch/restore three years ago. While they remain "experimental", there is no sign that they would be changed. Perhaps it is time to embrace the better version of git checkout.

PS: I did not change `release.sh`.

2022-11-14 13:24 UTC, asr requested changes
After a quick reading of [What's the difference between git switch and git checkout <branch>](https://stackoverflow.com/questions/57265785/whats-the-difference-between-git-switch-and-git-checkout-branch) it seems is a good idea to use `git switch` in these cases. Please also make the changes to `notes/agda-releases.txt`.

2022-11-14 18:00 UTC, andreasabel approved these changes

2022-11-15 10:26 UTC, asr approved these changes

2022-11-15 10:31 UTC, merged

2022-11-15 10:31 UTC, andreasabel commented
Thanks @favonia !