doc: Rename natEquals to _≡ᵇ_
agda/agda pull request #6352
Opened 2022-11-22 11:30 UTC by Lysxia

It's its name in `Data.Nat.Base`.

2022-11-22 11:33 UTC, Lysxia commented
huh the PDF build doesn't like unicode. that's a shame.

2022-11-22 21:19 UTC, gallais commented
Isn't it just a matter of adding the missing declarations in this file?
https://github.com/agda/agda/blob/master/doc/user-manual/unicode-symbols-sphinx.tex.txt

2022-11-23 07:21 UTC, andreasabel commented
Rendering at: https://agda--6352.org.readthedocs.build/en/6352/language/instance-arguments.html

2022-11-23 07:36 UTC, andreasabel requested changes

2022-11-23 07:36 UTC, andreasabel commented on doc/user-manual/language/instance-arguments.lagda.rst
> +    renaming (_==_ to _≡ᵇ_)
See my comments in the PR conversation.

2022-11-23 09:31 UTC, Lysxia commented
In this case it occurs exactly once, in the RHS of `eqNat`, so I think the context makes it quite unambiguous. Or how about adding the provenance as a comment next to it? I think if a reader wants to try this code, since the imports are not rendered, they will guess some modules to import, and if they guess `Data.Nat` then `_≡ᵇ_` will just work, unlike `natEquals`.

2022-11-23 09:35 UTC, andreasabel commented
> Or how about adding the provenance as a comment next to it?

This might be a solution!

2022-11-24 08:24 UTC, andreasabel approved these changes
Fine!

2022-11-24 08:25 UTC, merged