Fix #6379: Update warning messages
agda/agda pull request #6381
Opened 2022-12-04 17:30 UTC by felixwellen

2022-12-05 09:25 UTC, andreasabel requested changes
Thanks for the PR!

I took the liberty to review it even though it is still a draft.

2022-12-05 09:25 UTC, andreasabel commented on src/full/Agda/Interaction/Options/Warnings.hs
> +  WrongInstanceDeclaration_        -> "Terms marked as eligible for instance search should be of type {Γ} → C vs, where C evaluates to a postulated name or the name of a data or record type."
What about `{{x : A}}` domains? Should be fine for recursive instance search.
So maybe the description is: 
> ... `Γ → T` where `Γ` does not contain visible domains and `T` evaluates to ...

2022-12-05 09:25 UTC, andreasabel commented on src/full/Agda/TypeChecking/Pretty/Warning.hs
> +    WrongInstanceDeclaration -> fwords "Terms marked as eligible for instance search should be of type {Γ} → C vs, where C evaluates to a postulated name or the name of a data or record type, so `ins
Share parts of this explanation with the other occurrences, so that they stay in sync.

2022-12-05 09:25 UTC, andreasabel commented on src/full/Agda/TypeChecking/Pretty/Warning.hs
> +      pwords "Instance arguments whose type is not {Γ} → C vs, where C evaluates to a postulated name or the name of a data or record type, are never considered by instance search," ++
Share parts of this explanation with the other occurrences, so that they stay in sync.

2022-12-05 09:37 UTC, felixwellen commented on src/full/Agda/TypeChecking/Pretty/Warning.hs
> +    WrongInstanceDeclaration -> fwords "Terms marked as eligible for instance search should be of type {Γ} → C vs, where C evaluates to a postulated name or the name of a data or record type, so `ins
I wrongly thought, the changed explanations explain the same thing. This is not the case, allowed type when declaring instances are not the same as allowed types of instance arguments.

2022-12-05 09:48 UTC, andreasabel commented on src/full/Agda/TypeChecking/Pretty/Warning.hs
> +    WrongInstanceDeclaration -> fwords "Terms marked as eligible for instance search should be of type {Γ} → C vs, where C evaluates to a postulated name or the name of a data or record type, so `ins
Ok, sorry, didn't look close enough.

2022-12-05 09:50 UTC, andreasabel commented on src/full/Agda/Interaction/Options/Warnings.hs
> +  WrongInstanceDeclaration_        -> "Terms marked as eligible for instance search should be of type {Γ} → C vs, where C evaluates to a postulated name or the name of a data or record type."
Actually, at this very location not the full warning text is given, just a short summary what the warning is for.  This was probably wrong before you started changing it.

My suggestion for reformulation thus does not apply here, but at the other locations.

(Here, the formulation should be shortened.)

2022-12-05 19:18 UTC, andreasabel requested changes
Looks good.

I have some formulation suggestions.

2022-12-05 19:18 UTC, andreasabel commented on src/full/Agda/Interaction/Options/Warnings.hs
> +  WrongInstanceDeclaration_        -> "Instances should not be functions."
Mmh, not sure that "not functions" is the right qualification here...
How about: 
> Instances that do not adhere to the required format.

2022-12-05 19:18 UTC, andreasabel commented on src/full/Agda/TypeChecking/Pretty/Warning.hs
> +      "Instances should be of type {Γ} → C, where C is a postulated name or the name of " ++
"is" -> "evaluates to"  or "is equal to"

2022-12-05 19:18 UTC, andreasabel commented on src/full/Agda/TypeChecking/Pretty/Warning.hs
> +      pwords "Instance arguments whose type is not {Γ} → C, where C is a postulated type, a parameter type " ++
ditto

2022-12-06 16:40 UTC, andreasabel approved these changes
Excellent!

2022-12-06 17:46 UTC, merged

2022-12-06 17:47 UTC, andreasabel commented
Cherry-picked onto `release-2.6.3`.

2022-12-06 21:20 UTC, andreasabel commented
This PR broke `release-2.6.3`, but I pushed 03990274c7ba2051f8b4e577e3becec2e7ad9a14 to fix this.