Citation information
agda/agda pull request #6444
Opened 2023-01-18 14:02 UTC by L-TChen

GitHub has a built-in citation support. By placing the `CITATION.cff` file in the root of repostitory, GitHub will add a widget to the sidebar like this

<img width="376" alt="Screenshot 2023-01-18 at 21 51 45" src="https://user-images.githubusercontent.com/4060046/213188826-671c2cec-513f-42bd-9914-da100d95e1f3.png">

The file format is [here](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md)

It will be time-saving if it is clear how to cite Agda, so the remaing question is ... to agree on how Agda should be cited.

I draft one based on "Elaborating dependent (co)pattern matching: No pattern left behind" to kick off a discussion.

2023-01-18 14:05 UTC, L-TChen commented
For the demonstration purpose, I pushed the above file to my fork: https://github.com/L-TChen/agda, so you can see how it works on GitHub.

2023-01-18 14:30 UTC, gallais commented
Related discussions:

https://github.com/coq/coq/issues/5766
https://github.com/agda/agda-stdlib/issues/1833

2023-01-18 17:34 UTC, nad commented
For your demo I get the following BibTeX file:
```bibtex
@software{Agda_development_team_Agda_2_6_2_2_20230105_documentation,
author = {Agda development team},
title = {{Agda 2.6.2.2.20230105 documentation}},
url = {https://agda.readthedocs.io/en/v2.6.2.2.20230105/},
version = {2.6.2.2.20230105}
}
```
Is the idea to cite the *software* or its *documentation*?

For the documentation I think it makes sense to cite the user manual. The title of the user manual (the [PDF file](https://agda.readthedocs.io/_/downloads/en/latest/pdf/)) is currently "Agda User Manual, Release 2.6.4", and the author is "The Agda Team". However, I don't think we should recommend people to cite an unreleased user manual.

Something like the following BibTeX entry might be suitable for citing the Agda 2.6.2 documentation:
```bibtex
@Manual{Agda_manual:2_6_2,
  title =   {Agda User Manual, Release 2.6.2},
  author =  {{The Agda Team}},
  year =    {2021},
  url =     {https://agda.readthedocs.io/_/downloads/en/v2.6.2/pdf/},
  urldate = {2023-01-18}
}
```

2023-01-19 09:08 UTC, andreasabel commented
I think we should utilize the GitHub Releases feature also for the regular Agda releases (not just nightly) and then one could cite the release rather than the documentation.  Maybe we can get the help of Wen @wenkokke to get proper releases (with binaries) here.

2023-01-19 16:59 UTC, wenkokke commented
If I can use `setup-agda` for this, I could probably set this up pretty easily.

2023-02-02 05:11 UTC, L-TChen commented
Based on @andreasabel's suggestion, I update the `CITATION.cff` so that GitHub now produces 

```bibtex
@software{The_Agda_Team_Agda,
author = {The Agda Team},
title = {{Agda}},
url = {https://agda.readthedocs.io/en/v2.6.3/index.html},
version = {2.6.3}
}
```

For every release, one only needs to update the version (by `releash.sh`?). We may also want to include the citation instruction in the documentation.

2023-02-02 08:56 UTC, andreasabel approved these changes
LGTM (modulo I don't know what `cff` is).

2023-02-02 12:09 UTC, L-TChen commented
> LGTM (modulo I don't know what `cff` is).

lol

Right, if the citation format is agreed, then I will update the documentation and related scripts later (within this PR).

2023-02-02 19:03 UTC, nad commented
If we link to the documentation, then I think we should use the user manual's title, and not "Agda" (and `@manual` rather than `@software`). For some reason the PDF file and the collection of HTML files use different titles. I think this should be fixed.

I believe that BibTeX interprets `{The Agda Team}` as the first name `The Agda` and the last name `Team`. One can prevent this by using `{{The Agda Team}}`. I already used this format in the BibTeX entry that I gave above, which could be updated for Agda 2.6.3.

2023-02-03 14:31 UTC, L-TChen commented
I think it is more reasonable to cite the software instead of the documentation, see [here](https://www.software.ac.uk/how-cite-software) for reasons. As pointed by @gallais, it is possible to mint a DOI for software and archive source code in an open repository like Zenodo (supported by the EU and now used by many conferences including ICFP for artefact evaluation). 

Using `CITATION.cff` is not necessary at all. It is just to make life easier. As pointed by @nad, the implementation of the renderer is incorrect: I put “The Agda Team” as the family name, but the generated value is `{The Agda Team}` that will be treated by BibTeX as “Team, The Agda”.

Having a consistent citation format should make forward citation search easier. I find it difficult to find where Agda was used. If there is a DOI, then it should help Google Scholar or other analytic tools to locate.

Although I still do not know the best practice to cite a software like Agda, I’d like to propose the following:

1. Mint a conceptual DOI referring to all versions of Agda by releasing the initial version to Zenodo and mint a specific DOI for every release.
2. Instruct people to use the conceptual DOI but use the field `version` to specify the version. The citation may look like 

> The Agda Team. Agda (Version 2.6.3) [Computer software]. https://doi.org/xxx.yyy/zenodo.zzz

One may also include a link to the documentation. 

4. For convenience, provide a bibtex entry directly or via `CITATION.cff` if GitHub fixes the aboive issue. 

There are tools to convert a `.cff` file to a bibtex entry or other format, so it should be possible to update the citation instruction everywhere automatically.

2023-02-07 11:56 UTC, nad commented
> I think it is more reasonable to cite the software instead of the documentation

That depends on what the purpose of the citation is. Sometimes one may want to refer to the software, but sometimes one may want to, say, cite a passage in the user manual.

2023-02-10 02:51 UTC, Trebor-Huang commented
We can always just add citation instructions to readthedocs. For the repo I think the purpose is just to cite the software.

2024-02-11 21:41 UTC, andreasabel commented
I would think we should merge this PR rather than close it.  We can continue the bikeshedding even after this has been merged.  Having this PR in one form or the other is better than having nothing.

2024-02-11 21:45 UTC, andreasabel requested changes
This file needs to be added to the `change-version` script: https://github.com/agda/agda/blob/2816d755451ab97fb4c8021866dd557fc73354be/src/release-tools/change-version.bash#L11-L12

And to the exclude list in src/github/workflows/test.yml .

2024-02-11 22:52 UTC, wenkokke commented
> I think it is more reasonable to cite the software instead of the documentation, see [here](https://www.software.ac.uk/how-cite-software) for reasons. As pointed by @gallais, it is possible to mint a DOI for software and archive source code in an open repository like Zenodo (supported by the EU and now used by many conferences including ICFP for artefact evaluation). 
> 
> 
> 
> Using `CITATION.cff` is not necessary at all. It is just to make life easier. As pointed by @nad, the implementation of the renderer is incorrect: I put “The Agda Team” as the family name, but the generated value is `{The Agda Team}` that will be treated by BibTeX as “Team, The Agda”.
> 
> 
> 
> Having a consistent citation format should make forward citation search easier. I find it difficult to find where Agda was used. If there is a DOI, then it should help Google Scholar or other analytic tools to locate.
> 
> 
> 
> Although I still do not know the best practice to cite a software like Agda, I’d like to propose the following:
> 
> 
> 
> 1. Mint a conceptual DOI referring to all versions of Agda by releasing the initial version to Zenodo and mint a specific DOI for every release.
> 
> 2. Instruct people to use the conceptual DOI but use the field `version` to specify the version. The citation may look like 
> 
> 
> 
> > The Agda Team. Agda (Version 2.6.3) [Computer software]. https://doi.org/xxx.yyy/zenodo.zzz
> 
> 
> 
> One may also include a link to the documentation. 
> 
> 
> 
> 4. For convenience, provide a bibtex entry directly or via `CITATION.cff` if GitHub fixes the aboive issue. 
> 
> 
> 
> There are tools to convert a `.cff` file to a bibtex entry or other format, so it should be possible to update the citation instruction everywhere automatically. 
> 
> 
> 
> 
> 
> 

Following the specification, the Agda team should be cited as an entity rather than a person, so:
```cff
authors:
- name: "The Agda Team"
```

2024-02-11 22:54 UTC, wenkokke commented
Reading the specification, we should have the primary citation be for the software, but we could add a citation for the manual as a related work under the `references` key.

2024-02-12 05:30 UTC, L-TChen commented
> Following the specification, the Agda team should be cited as an entity rather than a person, so:
> 
> ```
> authors:
> - name: "The Agda Team"
> ```
Thanks! It does give the required BibTex entry as follows.

```
@software{The_Agda_Team_Agda,
author = {{The Agda Team}},
title = {{Agda}},
url = {https://agda.readthedocs.io/},
version = {2.6.5}
}
```

2024-02-16 15:19 UTC, L-TChen commented
> This file needs to be added to the `change-version` script:
> 
> https://github.com/agda/agda/blob/2816d755451ab97fb4c8021866dd557fc73354be/src/release-tools/change-version.bash#L11-L12
> 
> And to the exclude list in src/github/workflows/test.yml .

Yes, done. [ I don’t know why the requested change has not been marked resolved by GitHub … ]

2024-02-28 14:56 UTC, andreasabel commented on CITATION.cff
> +- name: "The Agda Team"
Make this just "Agda Developers".

2024-02-28 15:01 UTC, andreasabel commented
Please also update https://github.com/agda/agda/blob/d959b19d84f6ed61cb4f9e47c6e719c1404a8113/doc/user-manual/conf.py#L24

2024-02-28 15:03 UTC, andreasabel approved these changes

2024-03-05 04:54 UTC, L-TChen commented on CITATION.cff
> +- name: "The Agda Team"
Done!

2024-03-05 05:07 UTC, merged