Bump: GHC >= 8.6 (including shipped libs) and cabal-version >= 2.4
agda/agda pull request #6490
Opened 2023-01-30 18:32 UTC by andreasabel

Finally, with 2.6.3 release, we can drop some cruft!

Bump: GHC >= 8.6 (including shipped libs) and cabal-version >= 2.4.
This allows simplification of Agda.cabal by removing conditionals and introducing common stanzas.
All the GHC-shipped libs have a lower bound matching GHC 8.6.1 now.
I also took the opportunity to do a whitespace revolution.

2023-01-30 18:52 UTC, andreasabel commented on Agda.cabal
> +      -Werror=star-is-type
TODO: sort alphabetically

2023-01-30 18:52 UTC, andreasabel commented on Agda.cabal
> +license:         BSD-2-Clause
Is this the best match for our license?

2023-01-30 19:28 UTC, asr requested changes
> All the GHC-shipped libs have a lower bound matching GHC 8.6.1 now.

Since Agda doesn't build with GHC 8.6.1 due to a compiler error (see https://github.com/agda/agda/issues/3344), this version shouldn't be the lower bound matching. If fact, in `Agda.cabal` we only should use the latest versions (8.6.5, 8.8.4, etc.) that are supported.

2023-01-30 19:34 UTC, asr commented
I couldn't find the `.ghci*` file in `master`. @andreasabel, did you remove these files in other commit?

2023-01-30 19:40 UTC, andreasabel commented
> I couldn't find the `.ghci*` file in `master`. @andreasabel, did you remove these files in other commit?

If I recall correctly, @nad removed them recently:
commit beaabf4f68c2404b2b47fe49b0f6f9cee38e25b7
Date:   Fri Sep 9 15:51:44 2022 +0200
> Made "cabal repl tests" work by removing the .ghci files.

2023-01-30 19:51 UTC, andreasabel commented
> > All the GHC-shipped libs have a lower bound matching GHC 8.6.1 now.
> 
> Since Agda doesn't build with GHC 8.6.1 due to a compiler error (see #3344), this version shouldn't be the lower bound matching.

E.g., for all of GHC 8.6 there is only one `base`: 4.12.0.0.  There might be bumps in the other shipped libraries, I have not checked.
Bumping the shipped library lower bounds has little effect on building Agda, I suppose, since the constraint solver of cabal anyway prefers the shipped libraries.  I just did this because it was (mild) fun.

> If fact, in `Agda.cabal` we only should use the latest versions (8.6.5, 8.8.4, etc.) that are supported.

Not sure what is won by insisting on this.  Do you want to actively make Agda unbuildable for the intermediate GHC versions? 
Currently, we state in the CHANGELOG which versions we tested for; if you stray from these bounds, you are on your own. Don't you think this is sufficient?
We would anyway have to make an exception for the versions the still expect minor releases (currently 9.2 and 9.4), as we cannot force developers to always install the latest minor version.

2023-01-30 20:25 UTC, asr commented
> Not sure what is won by insisting on this. Do you want to actively make Agda unbuildable for the intermediate GHC versions?

No, of course. I was thinking in use the latest versions of GHC for setting up the warnings in `Agda.cabal`.

2023-01-30 21:01 UTC, andreasabel commented
>  I was thinking in use the latest versions of GHC for setting up the warnings in `Agda.cabal`.

Developers are recommended to use GHC >= 9 because the most important warnings are only switched on there (coverage checking).  But if you want to allow some flexibility on 9.2 and 9.4 there, you can only ban 9.0.1.

Anyway, my main concern with this PR was to drop GHC 8.0 - 8.4, so that we can save some CI instances and use new language features that came out in 8.6.

2023-01-30 22:02 UTC, asr commented
> Anyway, my main concern with this PR was to drop GHC 8.0 - 8.4, so that we can save some CI instances and use new language features that came out in 8.6.

I agree with drop those versions of GHC. My only concern is about a possible bug-fix release of 2.6.3. This bug-fix release should support the same versions than 2.6.3.

2023-01-31 07:23 UTC, andreasabel commented
> I agree with dropping those versions of GHC. My only concern is about a possible bug-fix release of 2.6.3. This bug-fix release should support the same versions than 2.6.3. If fact, we already have a milestone for it :-).

The bug-fix release should be done from the `release-2.6.3` branch, which still has all the GHC versions in its CI.

2023-01-31 11:05 UTC, asr commented
> The bug-fix release should be done from the `release-2.6.3` branch, which still has all the GHC versions in its CI.

If necessary, I suggest to create the `release-2.6.3.1` branch from the `release-2.6.3` branch.

Anyway, I was thinking in the possible incompatibilities when cherry-picking from `master` (with new language features) into `release-2.6.3.1`.

2023-01-31 16:18 UTC, andreasabel commented
> Anyway, I was thinking in the possible incompatibilities when cherry-picking from `master` (with new language features) into `release-2.6.3.1`.

Yes, but at some point we have to make a cut.  We decided to still support GHC 8.0 in Agda 2.6.3 because it is the official GHC of Ubuntu 18.04 LTS which reaches EOL only in April this year.  However, as soon as 18.04 is done, we need not support these old GHCs anymore, and we can even drop them in Agda 2.6.3.1.

For the bug-fix releases 2.6.2.1/2, I only cherry-picked commits that would cleanly pick and build without problems.  This would be my default also for 2.6.3.1, although super-critical fixes could be backported with some effort.

2023-01-31 16:34 UTC, andreasabel commented
@asr: Can we merge this now?  (You didn't make any _concrete_ suggestions on the changes.)

2023-02-01 08:39 UTC, andreasabel commented on Agda.cabal
> +license:         BSD-2-Clause
There is `LicenseRef-OtherLicense`

2023-02-01 17:05 UTC, merged