Enable erasure for equivalences
agda/agda pull request #6518
Opened 2023-03-09 04:35 UTC by cmcmA20

`Cubical.Foundations.*` transitive imports currently contain ~150 uses of `Glue` and `ua`. The change will make manual erasure annotation feasible for this restricted cubical library subset. Equivalences are ubiquitous and having them at runtime is highly desirable.

2023-03-10 00:29 UTC, cmcmA20 commented
Example usage: https://github.com/cmcmA20/cubical-mini/tree/global-erasure-v2

2023-03-10 19:48 UTC, plt-amy approved these changes

2023-03-11 19:44 UTC, andreasabel requested changes
@cmcmA20 : Thanks for this PR!
Changes to the primitive module structure should be documented in CHANGELOG.md.
Also please have a look whether the user manual has to be updated: https://github.com/agda/agda/blob/48fa602ad34edcde08252515db9b887197961ce0/doc/user-manual/language/cubical.lagda.rst

2023-03-11 21:38 UTC, cmcmA20 commented
Sorry I should've refrained from pressing unfamiliar buttons, I removed nad from reviewers somehow.

2023-03-12 01:18 UTC, cmcmA20 commented on doc/user-manual/language/cubical.lagda.rst
> -  {-# BUILTIN PATHTOEQUIV pathToEquiv #-}
It's long gone anyway, see 8864e3b2195b1bc38148ab1951837a35d92b412b

2023-03-12 23:12 UTC, andreasabel approved these changes
Thanks for the doc fixes!

2023-03-13 15:42 UTC, nad commented
This change makes sense to me.

2023-03-13 22:54 UTC, cmcmA20 commented
`Cubical.Foundations.HLevels.isOfHLevelSuc` fails to compile! First and third clauses are compiled correctly, second clause is a lambda w/o `coe` which seems wrong. If you manually insert coercions (in 3 places) in the generated code, it compiles succesfully.
Do not merge yet, I'm thinking about fix or better said trying to understand MAlonzo.

```
d_isOfHLevelSuc_180 ::
  MAlonzo.Code.Agda.Primitive.T_Level_14 ->
  () -> Integer -> AgdaAny -> AgdaAny
d_isOfHLevelSuc_180 v0 ~v1 v2 = du_isOfHLevelSuc_180 v0 v2
du_isOfHLevelSuc_180 ::
  MAlonzo.Code.Agda.Primitive.T_Level_14 ->
  Integer -> AgdaAny -> AgdaAny
du_isOfHLevelSuc_180 v0 v1
  = case coe v1 of
      0 -> coe
             MAlonzo.Code.Cubical.Foundations.Prelude.du_isContr'8594'isProp_1648
             (coe v0)
      1 -> \ v2 v3 v4 v5 v6 v7 v8 ->
             coe
               MAlonzo.Code.Cubical.Foundations.Prelude.du_isProp'8594'isSet_1658
               (coe v0) v2 v3 v4 v7 v8
      _ -> coe
             (\ v2 v3 v4 ->
                coe
                  du_isOfHLevelSuc_180 v0 (subInt (coe v1) (coe (1 :: Integer)))
                  (coe v2 v3 v4))
```

2023-03-14 08:34 UTC, andreasabel commented
@cmcmA20 : Could you add a test case for the compilation?  Tests are in `test/Compiler` (most are in `.../simple`) and it is usually not hard to add a new one.

2023-03-14 18:35 UTC, nad commented
Does the error related to compilation have anything to do with the other changes? If that bug is present in Agda 2.6.3, then I think it makes sense to open a separate ticket for it, so that it is properly documented.

2023-03-15 00:04 UTC, cmcmA20 commented
@nad You're right it's completely unrelated, I've opened a ticket https://github.com/agda/agda/issues/6530 and a PR for the fix https://github.com/agda/agda/pull/6531

2023-03-15 07:47 UTC, andreasabel commented
@nad: Fine to merge?  (NB: via **SQUASH**ing.)

2023-03-15 14:19 UTC, nad commented
> @nad: Fine to merge?

I have not tested the change, but as I wrote above it makes sense to me.

2023-03-15 23:29 UTC, andreasabel commented
@cmcmA20 : I see you did some more pushes.  Ping me whenever you think this PR is ready.

2023-03-15 23:30 UTC, cmcmA20 commented
It is, I've just rebased the changes onto current master

2023-03-15 23:33 UTC, andreasabel commented
Good, let's wait for CI to finish.

2023-03-16 00:11 UTC, merged