Refactor: Move Compiler/Treeless to Syntax/Treeless
agda/agda pull request #6680
Opened 2023-06-02 11:14 UTC by fredins

Hi! I wanted to make the following change to the pretty printing for `FunctionData`:
```haskell
-     , "funTreeless     =" <?> pshow funTreeless
+     , "funTreeless     =" <?> pretty funTreeless
```
However, this resulted in a lot of circular dependencies because of the orphaned instances in `Compiler/Treeless/Pretty` and `Compiler/Treeless/Subst`. I thought the best solution was to remove the orphaned instance by moving the instances (and all the other files in `Compiler/Treeless`) to the `Syntax` directory. This seems to better correspond with the other syntaxes (Abstract, Concrete, and Internal), and it also solves the "hack" in `Compiler/Backend.hs-boot`.

Alternatively, it is maybe feasible to solve this with `{-# SOURCE #-}` and `hs-boot` but I didn't find an easy way to do it.

Note: this is my first PR to Agda so I may be doing something wrong.

2023-06-02 11:48 UTC, jespercockx reviewed
Very nice first PR! This kind of change to improve the organization of Agda's modules is really welcome, see also https://github.com/agda/agda/issues/3512.

2023-06-02 11:48 UTC, jespercockx approved these changes

2023-06-02 15:23 UTC, andreasabel commented
Er, so I have to play the bad cop now and put the fly in the ointment...

I think only the very basic functionality for `Treeless` should reside under `Syntax` and the rest should stay under `Compiler`.
We also only have the most basic, universal functions of `Internal` under `Syntax` and the overwhelming majority is under `TypeChecking`.

I think the aim of your PR can be achieved with a much less invasive change.  It think most of the moving of modules does not contribute to solving your problem (avoiding boot files).  Please propose a minimal solution first.

2023-06-02 15:24 UTC, andreasabel requested changes
Thanks for the PR.

Please only do the minimal reorganization necessary to achieve your purpose (see my other comment).

2023-06-02 21:21 UTC, jespercockx commented
I'm not sure I agree it's better to put all stuff under `TypeChecking`, already it feels like 90% of the Agda codebase is there. For the other syntax classes a lot of stuff has indeed ended up there as well, but that does not mean it's indeed the best place for it. Are any of the functions in these modules actually doing "typechecking" in a meaningful way?

2023-06-03 07:22 UTC, andreasabel commented
I think roughly `TypeChecking` = `TCM` + `Syntax.Internal`, so, the non-tc-monadic stuff would go into `Agda.Syntax.Internal` and the rest into `TypeChecking`, sort of.

2023-07-21 14:32 UTC, andreasabel approved these changes
Thanks, sorry for the delay!

2023-07-21 14:32 UTC, merged