Re #6746: bump CI to GHC 9.8.1; treat `cache-hit` as string
agda/agda pull request #6924
Opened 2023-10-17 18:57 UTC by andreasabel

- Bump workflows except stack workflows (done already) to 9.8.1.

- `!steps.cache.output.cache-hit` does not do the expected thing:
  https://github.com/actions/cache/issues/1262
  Thus, use `!= 'true'` instead.

- Let the workflow `cabal-install.yml` use the preinstalled GHC and Cabal.

Closes #6746.

2023-10-17 20:02 UTC, asr requested changes
It seems you missed some steps from [ghc-releases.md](https://github.com/agda/agda/blob/master/notes/ghc-releases.md) before closing #6746 (e.g. the `tested-with` field in the cabal files was not updated nor the documentation in the CHANGELOG).

2023-10-17 21:07 UTC, andreasabel commented
> It seems you missed some steps from [ghc-releases.md](https://github.com/agda/agda/blob/master/notes/ghc-releases.md) before closing #6764 (e.g. the `tested-with` field in the cabal files was not updated nor the documentation in the CHANGELOG).

Well, I didn't expect we could move fully to 9.8.1 yet because usually one has to wait until `nightly` switches (or write a longing `stack.yaml` files with all dependencies listed).  That we can just use `nightly` is a novelty.  I expected we can make the transition in 3 months.
The correctness of the "tested-with" info should anyway be checked before the release.  I expect multiple changes to happen to this info until then.
That said, I will push another patch updating this info, after merging this workflow fix.

2023-10-17 21:15 UTC, merged

2023-10-17 21:17 UTC, andreasabel commented
Continued in 
- https://github.com/agda/agda/pull/6925

2023-10-17 22:33 UTC, asr commented
> > It seems you missed some steps from [ghc-releases.md](https://github.com/agda/agda/blob/master/notes/ghc-releases.md) before closing #6764 (e.g. the `tested-with` field in the cabal files was not updated nor the documentation in the CHANGELOG).
> 
> Well, I didn't expect we could move fully to 9.8.1 yet because usually one has to wait until `nightly` switches (or write a longing `stack.yaml` files with all dependencies listed). That we can just use `nightly` is a novelty. I expected we can make the transition in 3 months. The correctness of the "tested-with" info should anyway be checked before the release. I expect multiple changes to happen to this info until then. That said, I will push another patch updating this info, after merging this workflow fix.

I just think you closed the issue to early (but I understand the nice feeling of closing the goddamn issue after waiting for months for Agda compiles with GHC X.Y.Z :-) )

2023-10-18 06:25 UTC, andreasabel commented
> I just think you closed the issue to early (but I understand the nice feeling of closing the goddamn issue after waiting for months for Agda compiles with GHC X.Y.Z :-) )

Yes, indeed, it was after a late Friday work when I had revised many packages that Agda finally built with GHC 9.8.1, and I woke up Saturday thinking "oh, I forgot to close that issue" without remembering that I hadn't done any bumps for it...