Add a note about tc.unquote.decl/def verbosity to user manual
agda/agda pull request #6981
Opened 2023-11-10 10:47 UTC by UlfNorell

Closes #6963

2023-11-11 18:29 UTC, andreasabel approved these changes
Thanks!

2023-11-11 18:34 UTC, andreasabel requested changes

2023-11-11 18:34 UTC, andreasabel commented on doc/user-manual/language/reflection.lagda.rst
> +   when loading from an editor.
This should mention that these verbosities are always available even when Agda is not build with `-f debug`.
I had to look into the Agda sources to clarify this for me.

2023-11-12 16:47 UTC, andreasabel approved these changes
I added a sentence stating that these verbosity flags are available even without building Agda with `-f debug`.

2023-11-12 16:53 UTC, merged

2023-11-12 20:40 UTC, UlfNorell commented
I think you meant to write `Unlike other flags`, not `Unless other flags`.

2023-11-12 21:38 UTC, andreasabel commented
Oh bugger!