fix recRecursive when record isn't recursive
agda/agda pull request #7042
Opened 2023-12-24 14:19 UTC by flupe

A bug in agda/agda2hs#257 is caused by it relying on `TypeChecking/Monad/Base:recRecursive` which may fail when `recMutual` is set to `Nothing`.

2023-12-25 19:04 UTC, andreasabel requested changes
Not sure what you are after here, but I can't see how this makes sense.

If you want to query `recRecursive` before the mutuality computation has run, maybe you want to change the type to `Defn -> Maybe Bool`.

Currently, the invariant is that `recRecursive` is never queried before it has been set to `Just _`.

2023-12-25 19:04 UTC, andreasabel commented on src/full/Agda/TypeChecking/Monad/Base.hs
> +recRecursive (Record { recMutual = mqs }) = any (not . null) mqs
Well, the semantics of `recMutual = Nothing` is that nothing is known about mutualilty yet.
If you want _not mutual_ you have to make sure this gets set to `Just []`.

2023-12-25 19:51 UTC, flupe commented
Are you saying that all record definitions should have `recMutual` set to `Just` once typechecking is done?

Because the bug from agda2hs I'm refering to comes from a record definition compiled with the backend. We call `recRecursive` (presumably after typechecking is completed, since it's a backend compile hook) on the given record which definitely still has `recMutual` set to `False` when it reaches the backend.

2023-12-25 20:26 UTC, andreasabel commented
> We call `recRecursive` (presumably after typechecking is completed, since it's a backend compile hook) on the given record which definitely still has `recMutual` set to `False` when it reaches the backend.

(I think you meant to write `Nothing`, not `False`.)
Yes, `recRecursive` should be set latest once all checking phases are completed (type/coverage/termination... checking).

2023-12-26 11:40 UTC, flupe commented
Thank you for the clarification. So I guess there is still an issue with the record from agda/agda2hs#257 never getting `recMutual` populated by Agda before reaching the backend. I will investigate this later, closing this PR.

2023-12-26 11:40 UTC, closed without merging

2024-02-26 21:41 UTC, andreasabel commented
@flupe Maybe this PR fixes your problem in agda2hs:
- #7149

2024-02-27 09:13 UTC, flupe commented
Thank you for the heads up!