don't add generalizedTel definitions to mutual blocks
agda/agda pull request #7581
Opened 2024-10-20 09:04 UTC by UlfNorell

fixes #7530

2024-10-26 12:22 UTC, andreasabel approved these changes

2024-10-26 12:33 UTC, andreasabel commented
This change apparently triggers unsolved constraints in the `cubical` library: https://github.com/agda/agda/actions/runs/11425039173/job/31786434036?pr=7581#step:8:799
```
Cubical/Categories/Limits/RightKan.agda:109.13-203.41: error: [UnsolvedMetaVariables]
Unsolved metas at the following locations:
  ...
```

2024-10-26 12:34 UTC, andreasabel requested changes
Need some investigation why this triggers unsolved constraints.
Possibly a PR to `cubical` is needed before merging this.

2024-11-13 14:20 UTC, UlfNorell commented
I believe that what happens is that when more things are projection-like, lossy unification does less work, since a bunch of implicits are now erased and not available for comparison. Regardless, the changes required to cubical are fairly minor.

2024-11-13 22:14 UTC, andreasabel approved these changes

2024-11-14 06:01 UTC, merged